'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'FR' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Always start at 'FR' so the server render and the first client render match
  // (avoids a hydration mismatch). Browser/stored preference is applied after mount.
  const [language, setLanguageState] = useState<Language>('FR');

  useEffect(() => {
    const stored = localStorage.getItem('language');
    if (stored === 'FR' || stored === 'EN') {
      setLanguageState(stored);
    } else if (!navigator.language.startsWith('fr')) {
      setLanguageState('EN');
    }
  }, []);

  // Mirror the active language on <html lang> so search engines and screen
  // readers get the right one (it was hardcoded to "fr" before).
  useEffect(() => {
    document.documentElement.lang = language === 'FR' ? 'fr' : 'en';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  FR: {
    // Copy for the product-led landing redesign (desktop first). Kept in its own
    // `v2` block so the legacy section keys other pages still use stay untouched.
    // v3 landing (fiftyseven language) — FR
    v3: {
      scrollHint: 'Défiler',
      approachTitle1: 'Le soin',
      approachTitle2: 'vient à vous.',
      approachLabel: 'Notre approche',
      approachP2: 'Nous commençons dans le Grand Montréal, avec des infirmières membres de l\'OIIQ.',
      approachP3: 'Derrière chaque visite, une infirmière autorisée et un rapport clinique partagé après le soin.',
      visitCore: 'La visite',
      visitPara: 'Vous *décrivez le soin*. En *quelques minutes*, une infirmière *membre de l’OIIQ* est jumelée à vous. *Trois textos*, zéro appel. Le soin chez vous, puis le *rapport* et le *reçu*.',
      careTitle1: 'Des soins',
      careTitle2: 'chez vous.',
      card1Tag: '#PLAIES #POST-OP',
      card2Tag: '#DIABÈTE #HTA',
      card3Tag: '#SIGNES VITAUX',
      card4Tag: '#DÉPISTAGE',
      card5Tag: '#AÎNÉS',
      card6Tag: '#ORDONNANCE',
      dragBadge: 'Glisser',
      servicesAll: 'Voir tous les soins',
      backToTop: 'Haut',
      menu: 'Menu',
      close: 'Fermer',
      navigation: 'Navigation',
      skipToContent: 'Aller au contenu',
      notEmergency: 'MobiSoins n\'est pas un service d\'urgence. En cas d\'urgence, composez le 911.',
      prelaunch: 'Service en préparation : délais, zones et disponibilités seront confirmés au lancement.',
    },
    // Cookie / tracking consent panel (Law 25)
    consent: {
      caption: 'Témoins',
      title: 'Vos choix, vos données.',
      body: 'Nous utilisons des témoins essentiels au fonctionnement du site. Les témoins d’analyse et de marketing ne sont activés qu’avec votre consentement, que vous pouvez retirer en tout temps.',
      policyLink: 'Politique relative aux témoins',
      acceptAll: 'Tout accepter',
      rejectAll: 'Refuser',
      customize: 'Personnaliser',
      save: 'Enregistrer mes choix',
      close: 'Fermer',
      essential: 'Essentiels',
      essentialDesc: 'Nécessaires au fonctionnement du site : langue, choix de consentement. Toujours actifs.',
      analytics: 'Analytiques',
      analyticsDesc: 'Mesure d’audience pour améliorer le site. Désactivés par défaut.',
      marketing: 'Marketing',
      marketingDesc: 'Publicité et réseaux sociaux. Désactivés par défaut.',
      alwaysOn: 'Toujours actifs',
      gpcNote: 'Signal de confidentialité (GPC) détecté : les témoins non essentiels sont refusés par défaut.',
      manage: 'Gérer les témoins',
    },
    v2: {
      heroBadge: 'Infirmières autorisées OIIQ · Québec',
      heroCtaPrimary: 'Rejoindre la liste d\'attente',
      heroCtaSecondary: 'Voir comment ça marche',

      stepsTitle: 'Trois étapes, aucune salle d\'attente.',
      stepsEyebrow: 'Comment ça marche',
      step1Num: '01', step1Meta: '2 minutes', step1Title: 'Décrivez le soin',
      step1Opt1: 'Prise de sang', step1Opt2: 'Pansement / plaie', step1Opt3: 'Injection / vaccin',
      step1FootLabel: 'Aujourd\'hui', step1FootValue: '14 h 30',
      step2Num: '02', step2Meta: 'Jumelage rapide', step2Title: 'On trouve l\'infirmière',
      step2Chip: 'En route · 8 min', step2Licence: 'Membre de l’OIIQ',
      step3Num: '03', step3Meta: 'Après la visite', step3Title: 'Le soin, puis le rapport',
      step3Row1: 'Tension', step3Row2: 'Prélèvement',
      step3Row3: 'Transmis au médecin', step3Row3Value: 'Oui',
      step3Row4: 'Reçu d\'assurance', step3Row4Value: 'PDF',
      step3Cta: 'Télécharger',

      cred1Title: 'Infirmières membres de l’OIIQ',
      cred1Body: 'Chaque infirmière est membre de l’OIIQ, l’ordre professionnel des infirmières et infirmiers du Québec.',
      cred2Title: 'Données protégées',
      cred2Body: 'Dossiers hébergés au Canada, chiffrés et conçus pour respecter la Loi 25.',
      cred3Title: 'Assurance responsabilité',
      cred3Body: 'Nos infirmières détiennent une assurance responsabilité professionnelle.',
      cred4Title: 'Reçus détaillés',
      cred4Body: 'Reçu détaillé après chaque soin; le remboursement dépend de votre régime.',

      dispatchEyebrow: 'Répartition en direct',
      dispatchTitle1: 'Trois textos.',
      dispatchTitle2: 'Zéro appel.',
      dispatchBody: 'Pas de fenêtre de quatre heures. Vous savez qui vient, quand elle part et son heure d’arrivée estimée. Grand Montréal au lancement; zones et horaires confirmés dans l’application.',
      dispatchNote: 'Jumelage rapide avec des infirmières membres de l’OIIQ.',
      dispatchSms1Time: '14 h 03',
      dispatchSms1: 'Demande confirmée. Camille, infirmière autorisée OIIQ, sera chez vous vers 14\u00a0h\u00a040.',
      dispatchSms2Time: '14:31',
      dispatchSms2: 'Camille vient de partir. Répondez à ce message si vous devez lui laisser une consigne.',
      dispatchSms3Time: '14 h 36',
      dispatchSms3: 'Camille arrive dans environ 5 minutes.',
      dispatchThreadLabel: 'Exemple de textos reçus pendant une visite',

      servicesEyebrow: 'Soins offerts',
      servicesTitle: 'Ce qu\'une infirmière peut faire chez vous.',
      servicesNote: 'Certains soins peuvent être admissibles à un remboursement par votre assurance privée, selon votre régime. Reçu détaillé fourni après chaque visite.',
      patientsEyebrow: 'Nos patients',
      patientsTitle1: 'Les soins viennent',
      patientsTitle2: 'à ceux qui ne peuvent',
      patientsTitle3: 'plus se déplacer.',
      patientsBody: 'Aînés en perte d\'autonomie, patients en convalescence, familles sans voiture, proches aidants à bout de souffle. Pour eux, un rendez-vous en clinique coûte une demi-journée — et parfois un transport adapté.',
      nursesEyebrow: 'Pour les infirmières',
      nursesPitch: 'Choisissez vos quarts, vos secteurs et vos types de soins.',
      nursesCta: 'Rejoindre le réseau',

      ctaTitle1: 'Nous lançons bientôt',
      ctaTitle2: 'au Québec.',
      ctaBody: 'Inscrivez-vous pour être informé en premier du lancement dans votre secteur.',
      ctaButton: 'M\'inscrire',
      ctaFinePrint: 'Aucune carte requise. Désabonnement en tout temps.',
    },
    header: {
      home: 'Accueil',
      language: 'Langue',
      joinWaitlist: 'Liste d\'attente',
      about: 'À propos',
      howItWorks: 'Comment ça fonctionne',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Télécharger l\'app',
      recruitment: 'Recrutement',
      contact: 'Contact',
    },
    hero: {
      availableInQuebec: 'Disponible au Québec',
      title: 'Une infirmière chez vous,',
      titleHighlight: 'sans salle d’attente',
      subtitle: 'Des infirmières membres de l’OIIQ, réservées en quelques clics. Professionnel et sécuritaire.',
      subtitleShort: 'Des infirmières autorisées, réservées en quelques clics.',
      bookNow: 'Rejoindre la liste d\'attente',
      pitchDeck: 'Pitch deck',
      waitlistTitle: 'Liste d\'attente',
      waitlistSubtitle: 'Soyez informé en premier et obtenez',
      waitlistDiscount: '20 % de rabais',
      waitlistDiscountSuffix: 'au lancement.',
      emailPlaceholder: 'votre@courriel.com',
      successMessage: 'Inscrit!',
      errorMessage: 'Erreur',
      invalidEmail: 'Courriel invalide',
      personsRegistered: 'Personnes inscrites',
      patientsServed: 'Patients traités',
      nextAppointment: 'Prochain soin',
      highlights: 'Faits saillants',
      satisfaction: 'Satisfaction',
      network: 'Réseau',
      nurses: 'Infirmières',
      zone: 'Zone',
      quebec: 'Grand Montréal',
      continueButton: 'Continuer',
      or: 'OU',
      continueWithApple: 'Continuer avec Apple',
      continueWithGoogle: 'Continuer avec Google',
      continueWithEmail: 'Continuer avec une adresse courriel',
      findAccount: 'Retrouver votre compte',
      phoneNumber: 'Numéro de téléphone',
      getStarted: 'Commencer avec MobiSoins',
    },
    howItWorks: {
      title: 'Comment ça fonctionne?',
      subtitle: 'MobiSoins simplifie l\'accès aux soins de santé à domicile.',
      step1Title: 'Réservez en quelques clics',
      step1Description: 'Choisissez votre soin et l\'heure qui vous conviennent, puis confirmez votre adresse. Nous trouvons les infirmières disponibles près de vous.',
      step2Title: 'Jumelage et suivi en temps réel',
      step2Description: 'Nous vous jumelons à une infirmière qui correspond à vos besoins. Suivez son déplacement vers vous sur la carte, en temps réel.',
      step3Title: 'Soins professionnels à domicile',
      step3Description: 'Recevez des soins de qualité dans le confort de votre domicile. Rapport clinique disponible dans l\'application après chaque visite.',
      step1: {
        title: 'Réservez en quelques clics',
        description: 'Choisissez votre soin et l\'heure qui vous conviennent, puis confirmez votre adresse. Nous trouvons les infirmières disponibles près de vous.',
      },
      step2: {
        title: 'Jumelage et suivi en temps réel',
        description: 'Nous vous jumelons à une infirmière qui correspond à vos besoins. Suivez son déplacement vers vous sur la carte, en temps réel.',
      },
      step3: {
        title: 'Soins professionnels à domicile',
        description: 'Recevez des soins de qualité dans le confort de votre domicile. Rapport clinique disponible dans l\'application après chaque visite.',
      },
    },
    services: {
      badge: 'Nos avantages',
      seeAll: 'Voir tous nos services',
      mainTitle: 'Votre santé mérite',
      mainTitlePrefix: 'des',
      mainTitleHighlight: 'services',
      mainTitleSuffix: 'complets',
      card1Visual: 'Tableau de bord',
      card1Item1: 'Prochain rendez-vous',
      card1Item1Detail: 'Demain, 14 h',
      card1Item2: 'Médicaments',
      card1Item2Detail: 'Pris à 8 h',
      card1Badge: 'Suivi personnalisé',
      card1Title: 'Tout au même endroit',
      card1Description: 'Gérez vos rendez-vous, suivez vos ordonnances et consultez votre historique de soins en un clin d\'œil.',
      card1Point1: 'Rappels de rendez-vous et de médicaments',
      card1Point2: 'Historique de soins complet dans l\'application',
      card1Point3: 'Rapports cliniques numériques partageables',
      card2Visual: 'Recherche intelligente',
      card2Badge: 'Jumelage précis',
      card2Title: 'Trouvez l\'experte idéale',
      card2Description: 'Nous vous jumelons à une infirmière qualifiée près de chez vous.',
      card2Point1: 'Infirmières membres de l\'OIIQ',
      card2Point2: 'Jumelage rapide',
      card2Point3: 'Plages horaires selon vos disponibilités',
      card3Visual: 'Vos données',
      card3Badge: 'Suivi clinique',
      card3Title: 'Suivez votre historique de soins',
      card3Description: 'L’application vous permettra de suivre votre historique de soins et de partager vos rapports.',
      card3Point1: 'Prises de sang, soins de plaies et injections',
      card3Point2: 'Soins postopératoires, gériatriques et pédiatriques',
      card3Point3: 'Suivi des visites et des signes vitaux en temps réel',
      mapBadge: 'Lancement dans le Grand Montréal',
      bannerTitle: 'Soins à domicile, d\'abord',
      bannerTitleHighlight: 'dans le Grand Montréal.',
      bannerDescription: 'Infirmières membres de l\'OIIQ, d\'abord dans la grande région de Montréal, puis dans d\'autres régions du Québec au fil de notre croissance.',
      bannerCta: 'Rejoindre la liste d\'attente',
    },
    patients: {
      titleStart: 'Des soins qui font',
      titleItalic: 'sourire.',
      caption1: 'Visite à domicile · Rosemont',
      caption2: 'Vaccination · Laval',
      imageAlt1: 'Infirmière MobiSoins rendant visite à une famille à domicile',
      imageAlt2: 'Infirmière MobiSoins vaccinant une enfant',
      badge: 'Nos patients',
      title: 'Des soins qui font sourire',
      subtitle: 'Chaque jour, nos infirmières apportent des soins professionnels et humains directement au domicile de nos patients.',
      description: 'Prise de sang, suivi postopératoire, administration de médicaments, soins de plaies ou simplement une présence rassurante : MobiSoins accompagne chaque patient avec professionnalisme et bienveillance, à chaque étape de son rétablissement. Nos infirmières membres de l\'OIIQ se déplacent dans la grande région de Montréal pour offrir des soins de qualité, sans le stress ni les déplacements.',
      point1Title: 'Soins personnalisés',
      point1Desc: 'Chaque plan de soins est adapté aux besoins précis du patient, dans le confort de son domicile.',
      point2Title: 'Zéro déplacement',
      point2Desc: 'Fini les longues attentes en clinique. L\'infirmière se déplace directement chez vous.',
      point3Title: 'Suivi clinique complet',
      point3Desc: 'Un rapport détaillé après chaque visite, partagé avec le patient et ses proches.',
      point4Title: 'Accompagnement humain',
      point4Desc: 'Nos infirmières prennent le temps d\'écouter, d\'expliquer et de rassurer.',
    },
    location: {
      name: 'Montréal, Québec',
      caption: 'Lancement à Montréal · Grand Montréal d\'abord',
      eyebrow: 'Couverture',
      titleStart: 'Montréal d\'abord,',
      titleItalic: 'puis partout au Québec.',
      lede: 'Nous lançons l\'app d\'abord dans le Grand Montréal. Inscrivez votre ville sur la liste d\'attente et nous vous écrirons le jour où les réservations ouvriront chez vous.',
      row1Label: 'Lancement',
      row1Value: 'Montréal · Laval · Longueuil',
      row2Label: 'Liste d\'attente',
      row2Value: 'Québec · Gatineau · Sherbrooke',
      cta: 'Inscrire ma ville',
    },
    map: {
      titleStart: 'Des soins à domicile',
      titleItalic: 'en quelques minutes.',
      label1: 'Jumelage',
      label2: 'Infirmières',
      label3: 'Suivi',
      eta: 'Arrivée dans 8 min',
      imageAlt: 'Infirmière MobiSoins au volant, en route vers un patient',
      badge: 'Répartition en temps réel',
      title: 'Des soins à domicile, rapidement',
      description: 'Nous jumelons chaque patient à une infirmière membre de l’OIIQ disponible près de chez lui.',
      bullet1: 'Jumelage automatique et rapide',
      bullet1Sub: 'Nous trouvons une infirmière disponible près de chez vous.',
      bullet2: 'Infirmières membres de l\'OIIQ',
      bullet2Sub: 'Chaque professionnelle est validée au tableau de l\'Ordre.',
      bullet3: 'Suivi GPS en temps réel',
      bullet3Sub: 'Suivez le déplacement de votre infirmière jusqu\'à votre porte.',
      footnote: 'Lancement dans le Grand Montréal',
      stepBooked: 'Réservé',
      stepMatched: 'Jumelé',
      stepEnRoute: 'En route',
      stepArrived: 'Arrivé',
      trackTitle: 'Suivi de la visite',
    },
    blog: {
      badge: 'Notre blogue',
      title: 'Derniers articles',
      subtitle: 'Restez au fait des dernières actualités en santé, des conseils de nos experts et des innovations MobiSoins.',
      readMore: 'Lire l\'article',
      readTime: 'de lecture',
      article1Tag1: 'Innovation santé',
      article1Tag2: 'Télésanté',
      article1Title: 'Comment la télésanté transforme le suivi médical',
      article1Description: 'Et si consulter un professionnel de la santé devenait aussi simple qu\'un appel vidéo? La télésanté transforme le suivi médical en profondeur.',
      article2Tag1: 'Guide pratique',
      article2Tag2: 'Domicile',
      article2Title: 'Comment bien se préparer à sa première visite avec MobiSoins',
      article2Description: 'Recevoir des soins infirmiers à domicile, c\'est bénéficier d\'un suivi professionnel directement dans son environnement.',
      article3Tag1: 'Tendance santé',
      article3Tag2: 'Aînés',
      article3Title: 'Les avantages des soins à domicile pour les aînés',
      article3Description: 'Et si le meilleur endroit pour vieillir n\'était pas l\'hôpital… mais tout simplement chez soi?',
    },
    faq: {
      title: 'Questions fréquentes',
      subtitle: 'Trouvez des réponses à vos questions les plus courantes',
      ctaPrompt: 'Une question? Consultez notre foire aux questions.',
      ctaButton: 'Voir la FAQ',
      searchPlaceholder: 'Rechercher une question...',
      noResults: 'Aucune question trouvée pour votre recherche.',
      question1: 'Comment fonctionne MobiSoins?',
      answer1: 'MobiSoins jumelle les patients à des infirmières membres de l\'OIIQ pour des soins à domicile. Vous réservez dans l\'application, suivez votre infirmière en temps réel, puis payez de façon sécuritaire une fois le soin terminé.',
      question2: 'Les infirmières sont-elles vraiment qualifiées?',
      answer2: 'Oui. Toutes nos infirmières sont membres de l’Ordre des infirmières et infirmiers du Québec (OIIQ) et détiennent une assurance responsabilité professionnelle.',
      question3: 'Quels sont les coûts?',
      answer3: 'Les prix varient selon le soin. Le prix exact s\'affiche avant la réservation, sans frais cachés. Paiement sécurisé par carte de crédit ou Apple Pay.',
      question4: 'Quelles régions sont couvertes?',
      answer4: 'Nous lançons d\'abord le service dans la grande région de Montréal, avec l\'objectif de l\'étendre ensuite à d\'autres régions du Québec. Inscrivez votre ville sur la liste d\'attente pour être informé du lancement chez vous.',
      question5: 'Comment devenir infirmière partenaire?',
      answer5: 'Inscrivez-vous à la liste d\'attente en tant qu\'infirmière. Nous vérifions votre inscription au tableau de l\'OIIQ et votre assurance, puis nous vous rencontrons en entrevue avant vos premières visites.',
      question6: 'Les paiements sont-ils sécurisés?',
      answer6: 'Oui. Tous les paiements sont traités par un fournisseur de paiement sécurisé et nous ne stockons jamais vos informations bancaires.',
      question7: 'Puis-je choisir mon infirmière?',
      answer7: 'Vous pouvez consulter le profil, les évaluations et l\'expérience de l\'infirmière avant de confirmer la visite. Si vous avez une préférence, vous pouvez demander la même infirmière pour vos prochaines visites.',
      question8: 'Que se passe-t-il en cas d\'urgence médicale?',
      answer8: 'MobiSoins n\'est PAS un service d\'urgence. En cas d\'urgence vitale, composez le 911. Nos infirmières prennent en charge les soins non urgents et peuvent vous orienter vers l\'urgence au besoin.',
    },
    contact: {
      title: 'Contactez-nous',
      description: 'Nous sommes là pour vos questions, commentaires ou propositions de partenariat. Nous vous répondons dans les plus brefs délais.',
      detailsTitle: 'Coordonnées',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'Courriel',
      web: 'Web',
      firstName: 'Prénom',
      firstNamePlaceholder: 'Prénom',
      lastName: 'Nom',
      lastNamePlaceholder: 'Nom',
      emailLabel: 'Courriel',
      emailPlaceholder: 'votre@courriel.com',
      subject: 'Sujet',
      subjectPlaceholder: 'Comment pouvons-nous vous aider?',
      message: 'Message',
      messagePlaceholder: 'Décrivez votre demande en détail...',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      sent: '✓ Message envoyé!',
      sentConfirm: 'Merci! Nous vous répondrons dans les plus brefs délais.',
      errorGeneric: 'Une erreur est survenue. Veuillez réessayer ou nous écrire à info@mobisoins.com.',
      errorConfig: 'Le formulaire n\'est pas encore configuré. Écrivez-nous à info@mobisoins.com.',
    },
    stats: {
      patients: 'Patients servis',
      nurses: 'Infirmières de l\'OIIQ',
      satisfaction: 'Satisfaction',
      availability: 'Disponibilité',
      cities: 'Villes au Québec',
    },
    newsletter: {
      title: 'Rejoignez la liste d\'attente',
      subtitle: 'Commencez dès aujourd\'hui.',
      cta: 'S\'inscrire maintenant',
      description: 'Soyez informé du lancement de MobiSoins dans votre secteur.',
      emailPlaceholder: 'votre@courriel.com',
      submitButton: 'M\'inscrire',
      submitting: 'Envoi...',
      successTitle: 'Merci!',
      successMessage: 'Vous êtes inscrit à la liste d\'attente.',
      errorTitle: 'Erreur',
      errorMessage: 'Une erreur s\'est produite. Veuillez réessayer.',
      invalidEmailTitle: 'Courriel invalide',
      priorityAccess: 'Accès prioritaire',
      noCardRequired: 'Aucune carte requise',
    },
    visit: {
      eyebrow: 'Une visite, minute par minute',
      titleStart: 'Voici à quoi ressemble',
      titleItalic: 'un mardi après-midi.',
      lede: 'Une prise de sang pour une patiente de 74 ans à Rosemont, réservée par sa fille depuis le bureau.',
      step1Title: 'Réservé',
      step1Text: 'Prise de sang, aujourd\'hui, entre 14 h 30 et 16 h. Prix confirmé à l\'écran.',
      step2Title: 'Infirmière jumelée',
      step2Text: 'Marie-Ève accepte. Son profil, sa note et son heure d\'arrivée s\'affichent dans l\'app.',
      step3Title: 'À la porte',
      step3Text: 'Sa fille reçoit une notification au travail. La visite dure environ 20 minutes.',
      step4Title: 'Rapport dans l\'app',
      step4Text: 'Note clinique partagée avec la famille et le médecin traitant. Reçu envoyé pour les assurances.',
      caption: 'Visite en cours',
      imageAlt: 'Une infirmière MobiSoins applique un pansement sur le bras d\'une dame âgée dans son salon',
    },
    waitlist: {
      eyebrow: 'Liste d\'attente',
      titleStart: 'Soyez en tête de file quand l\'app arrivera',
      titleItalic: 'dans votre ville.',
      lede: 'Laissez-nous votre courriel : un seul message à l\'ouverture des réservations près de chez vous — rien d\'autre.',
      social: 'Des patients et des infirmières déjà sur la liste',
      firstName: 'Prénom',
      firstNamePlaceholder: 'Nathalie',
      city: 'Ville',
      otherCity: 'Autre ville',
      email: 'Courriel',
      emailPlaceholder: 'vous@exemple.com',
      role: 'Je m\'inscris en tant que',
      rolePatient: 'Patient ou proche',
      roleNurse: 'Infirmière (membre de l\'OIIQ)',
      roleEmployer: 'Employeur ou clinique',
      submit: 'Rejoindre la liste d\'attente',
      done: 'Vous êtes sur la liste',
      note: 'Un seul courriel au lancement. Désabonnement en tout temps.',
      error: 'Une erreur s\'est produite. Veuillez réessayer.',
    },
    about: {
      badge: 'À propos',
      title: 'À propos',
      missionBadge: 'Notre mission',
      missionTitle: 'Des soins accessibles, où que vous soyez dans le Grand Montréal.',
      missionLead: 'Au Québec, obtenir des soins simples peut exiger des heures d\'attente, parfois des jours. MobiSoins existe pour changer cela. Nous apportons l\'expertise clinique directement au domicile des patients, rapidement et en toute sécurité.',
      statementBadge: 'Notre engagement',
      statement1: 'La mission de MobiSoins est de rendre des soins de santé de qualité plus accessibles en offrant des soins sûrs, professionnels et empreints de compassion, directement au domicile des patients, grâce à une plateforme numérique innovante.',
      statement2: 'Nous croyons que personne ne devrait avoir à patienter des heures dans une clinique bondée, ni à traverser la ville, pour recevoir des soins qui peuvent très bien être prodigués là où l\'on vit. En jumelant les patients à des infirmières membres de l\'OIIQ en quelques minutes, MobiSoins efface la distance entre une personne et les soins dont elle a besoin, qu\'il s\'agisse d\'une prise de sang, d\'un pansement, du suivi d\'une maladie chronique ou d\'une visite rassurante auprès d\'un proche.',
      statement3: 'Derrière chaque visite se trouve une équipe qui unit expertise clinique et technologie moderne. Nos infirmières respectent les plus hauts standards de pratique, et notre plateforme rend chaque étape transparente, de la réservation jusqu\'au rapport clinique partagé après la visite. C\'est ainsi que nous bâtissons la confiance, un domicile et un patient à la fois, partout au Québec.',
      problemBadge: 'Le problème',
      problemTitle: 'Un système sous pression, des patients laissés de côté.',
      problemText1: 'Les urgences débordent, les listes d\'attente s\'allongent et une population vieillissante a besoin de soins de plus en plus fréquents. Pour un simple pansement, une prise de sang ou un suivi, des milliers de personnes se déplacent, patientent et perdent un temps précieux.',
      problemText2: 'Pendant ce temps, des infirmières hautement qualifiées manquent d\'outils modernes pour rejoindre efficacement les patients qui ont besoin d\'elles. Le talent existe. La demande existe. Ce qui manquait, c\'était le lien entre les deux.',
      problemText3: 'C\'est précisément pour combler cet écart que MobiSoins a été fondée à Montréal en 2025, par une équipe réunissant plus de 36 années d\'expérience infirmière combinée et des ingénieurs issus de grandes entreprises technologiques comme Microsoft, IBM et Constellation Software.',
      storyBadge: 'Notre histoire',
      storyTitle: 'Tout a commencé par une attente de deux jours.',
      storyText1: 'En septembre 2025, à Montréal, l\'un de nos fondateurs a vu sa mère passer deux journées entières à l\'hôpital. Pas pour une chirurgie, ni pour quoi que ce soit de complexe. Elle attendait un Tylenol et un billet médical. Deux jours, pour quelque chose qui aurait dû prendre quelques minutes. Cette attente a été l\'étincelle de MobiSoins.',
      storyText2: 'Quatre personnes qui avaient vu ce problème des deux côtés ont décidé d\'y remédier. Deux infirmières cliniciennes cumulant plus de 36 années d\'expérience au chevet des patients, et deux ingénieurs logiciels ayant bâti des systèmes à grande échelle chez Microsoft, IBM et Constellation Software. Ils se sont rencontrés par l\'entremise de connaissances communes, partageaient la même frustration et ont fondé MobiSoins ensemble, à parts égales.',
      storyText3: 'Le problème va dans les deux sens. Les patients attendent beaucoup trop longtemps pour des soins qui pourraient facilement venir à eux, et les infirmières qui prodiguent ces soins sont trop souvent sous-évalués et sous-payés pour leur expertise. MobiSoins a été créée pour corriger les deux. Nous offrons des soins sûrs, professionnels et empreints de compassion aux patients de tout âge, et nous donnons aux infirmières une meilleure façon, plus juste, d\'exercer.',
      storyText4: 'Nous commençons au Québec, mais notre ambition ne s\'arrête pas là. Notre objectif est de nous étendre à l\'échelle nationale, puis partout dans le monde, afin que chacun, où qu\'il soit, puisse recevoir des soins de qualité dans le confort de son domicile.',
      storyQuote: 'Personne ne devrait attendre deux jours pour un Tylenol.',
      foundersLabel: 'Les fondateurs',
      founderRole: 'Cofondateur',
      foundersTitle: 'Quatre personnes, deux côtés du même problème.',
      foundersLead: 'Deux infirmières cliniciennes et deux ingénieurs logiciels, réunis par la même frustration et associés à parts égales.',
      founderFrom: 'Origine',
      founderPrev: 'Parcours',
      founderPhotoPending: 'Portrait à venir',
      ctaTitle: 'Envie de recevoir des soins à la maison?',
      ctaBody: 'Rejoignez la liste d’attente et soyez informé du lancement dans votre secteur.',
      ctaButton: 'Rejoindre la liste d’attente',
      fact1Value: '36+',
      fact1Label: 'Années d\'expérience infirmière combinées',
      fact2Value: '2025',
      fact2Label: 'Fondée à Montréal, Québec',
      fact3Value: 'Big tech',
      fact3Label: 'Ingénierie issue de Microsoft, IBM et Constellation',
      teamBadge: 'Notre équipe',
      teamTitle: 'Le soin et la technologie, côte à côte.',
      teamLead: 'Impossible d\'améliorer les soins de santé sans réunir ceux qui les prodiguent et ceux qui conçoivent les outils. C\'est pourquoi nos infirmières et nos ingénieurs travaillent au sein d\'une même équipe, vers un même objectif.',
      team1Title: 'Rigueur clinique',
      team1Desc: 'Des infirmières membres de l\'OIIQ définissent chaque protocole de soins et valident chaque fonctionnalité avant qu\'elle n\'atteigne un patient.',
      team2Title: 'Ingénierie solide',
      team2Desc: 'Une équipe technique bâtit une plateforme rapide, fiable et sécuritaire, du jumelage en temps réel jusqu\'au dossier clinique.',
      team3Title: 'Ancrage terrain',
      team3Desc: 'Nos opérations restent proches des patients et des infirmières pour améliorer le service en continu, une visite à la fois.',
      valuesBadge: 'Nos valeurs',
      valuesTitle: 'Ce qui nous guide',
      value1Title: 'Accessibilité',
      value1Desc: 'Des soins de qualité pour tous, partout au Québec, sans les longues attentes.',
      value2Title: 'Humanité',
      value2Desc: 'La personne au cœur de chaque intervention, avec écoute et bienveillance.',
      value3Title: 'Excellence clinique',
      value3Desc: 'Des infirmières membres de l\'OIIQ, tenues aux plus hauts standards de pratique.',
      value4Title: 'Innovation',
      value4Desc: 'La technologie au service de soins plus rapides, sûrs et transparents.',
      description1: 'MobiSoins est une clinique mobile offrant des soins infirmiers professionnels à domicile et en ligne.',
      description2: 'Fondée par deux infirmières cliniciennes, MobiSoins a pour mission de rendre les soins de santé plus accessibles, rapides et sécuritaires, tout en plaçant la personne au cœur de chaque intervention.',
      description3: 'Grâce à une approche moderne alliant expertise clinique et innovation, nous offrons des services adaptés aux besoins de la population, dans le respect des plus hauts standards de pratique.',
      servicesTitle: 'Services',
      servicesIntro: 'MobiSoins offre une gamme complète de soins infirmiers adaptés à vos besoins, à domicile ou en ligne.',
      insuranceNote: 'Certains services peuvent être admissibles, selon votre régime, au remboursement par les assurances privées. Reçus officiels fournis.',
      service1Title: 'Soins infirmiers',
      service1Desc: 'Pansements, retrait de points, administration de médicaments, soins postopératoires et suivi clinique.',
      service2Title: 'Suivi des maladies chroniques',
      service2Desc: 'Suivi du diabète, de l\'hypertension et d\'autres affections, avec enseignement et prévention des complications.',
      service3Title: 'Bilan de santé',
      service3Desc: 'Évaluation complète, prise des signes vitaux et conseils personnalisés pour votre santé.',
      service4Title: 'Santé sexuelle',
      service4Desc: 'Dépistage des ITSS, contraception, éducation et suivi.',
      service5Title: 'Soins aux aînés',
      service5Desc: 'Surveillance de la santé, gestion de la médication et soutien à domicile.',
      service6Title: 'Analyses et prélèvements',
      service6Desc: 'Prélèvements sanguins et tests diagnostiques, sur ordonnance.',
      service7Title: 'Services aux entreprises',
      service7Desc: 'Cliniques mobiles, bilans de santé et programmes de prévention en milieu de travail.',
    },
    logoCloud: {
      title: 'Partenaires de confiance au Québec',
    },
    footer: {
      product: 'Produit',
      howItWorks: 'Comment ça fonctionne',
      articles: 'Articles',
      faq: 'FAQ',
      social: 'Réseaux sociaux',
      madeIn: 'Fait avec soin au Québec',
      description: 'Une plateforme de soins infirmiers à domicile dans la grande région de Montréal. Nous jumelons des infirmières membres de l\'OIIQ à des patients rapidement.',
      company: 'Entreprise',
      aboutUs: 'À propos',
      press: 'Presse',
      blog: 'Blogue',
      services: 'Services',
      forPatients: 'Pour les patients',
      forNurses: 'Pour les infirmières',
      pricing: 'Tarification',
      insurance: 'Assurances',
      support: 'Soutien',
      helpCenter: 'Centre d\'aide',
      contact: 'Contact',
      privacy: 'Confidentialité',
      terms: 'Conditions',
      legal: 'Mentions légales',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d\'utilisation',
      cookies: 'Politique sur les témoins',
      allRightsReserved: 'Tous droits réservés.',
    },
  },
  EN: {
    // v3 landing (fiftyseven language) — EN
    v3: {
      scrollHint: 'Scroll',
      approachTitle1: 'Care',
      approachTitle2: 'comes to you.',
      approachLabel: 'Our approach',
      approachP2: 'We start in Greater Montreal, with OIIQ-licensed nurses.',
      approachP3: 'Behind every visit, a licensed nurse and a clinical report shared afterward.',
      visitCore: 'The visit',
      visitPara: 'You *describe the care*. Within *minutes*, an *OIIQ-member* nurse is matched to you. *Three texts*, zero phone calls. Care at home, then the *report* and the *receipt*.',
      careTitle1: 'Care,',
      careTitle2: 'at home.',
      card1Tag: '#WOUNDS #POST-OP',
      card2Tag: '#DIABETES #BP',
      card3Tag: '#VITALS',
      card4Tag: '#SCREENING',
      card5Tag: '#SENIORS',
      card6Tag: '#PRESCRIPTION',
      dragBadge: 'Drag',
      servicesAll: 'See all services',
      backToTop: 'Top',
      menu: 'Menu',
      close: 'Close',
      navigation: 'Navigate',
      skipToContent: 'Skip to content',
      notEmergency: 'MobiSoins is not an emergency service. In an emergency, call 911.',
      prelaunch: 'Service in preparation: wait times, zones and availability will be confirmed at launch.',
    },
    // Cookie / tracking consent panel (Law 25)
    consent: {
      caption: 'Cookies',
      title: 'Your choices, your data.',
      body: 'We use cookies that are essential to run the site. Analytics and marketing cookies are only enabled with your consent, which you can withdraw at any time.',
      policyLink: 'Cookie policy',
      acceptAll: 'Accept all',
      rejectAll: 'Refuse',
      customize: 'Customize',
      save: 'Save my choices',
      close: 'Close',
      essential: 'Essential',
      essentialDesc: 'Required for the site to work: language, consent choice. Always on.',
      analytics: 'Analytics',
      analyticsDesc: 'Audience measurement to improve the site. Off by default.',
      marketing: 'Marketing',
      marketingDesc: 'Advertising and social media. Off by default.',
      alwaysOn: 'Always on',
      gpcNote: 'Privacy signal (GPC) detected: non-essential cookies are refused by default.',
      manage: 'Manage cookies',
    },
    v2: {
      heroBadge: 'OIIQ-licensed nurses · Quebec',
      heroCtaPrimary: 'Join the waitlist',
      heroCtaSecondary: 'See how it works',

      stepsTitle: 'Three steps, no waiting room.',
      stepsEyebrow: 'How it works',
      step1Num: '01', step1Meta: '2 minutes', step1Title: 'Describe the care',
      step1Opt1: 'Blood draw', step1Opt2: 'Wound / dressing', step1Opt3: 'Injection / vaccine',
      step1FootLabel: 'Today', step1FootValue: '2:30 PM',
      step2Num: '02', step2Meta: 'Fast matching', step2Title: 'We find the nurse',
      step2Chip: 'On the way · 8 min', step2Licence: 'OIIQ member',
      step3Num: '03', step3Meta: 'After the visit', step3Title: 'The care, then the report',
      step3Row1: 'Blood pressure', step3Row2: 'Sample',
      step3Row3: 'Sent to your doctor', step3Row3Value: 'Yes',
      step3Row4: 'Insurance receipt', step3Row4Value: 'PDF',
      step3Cta: 'Download',

      cred1Title: 'OIIQ-member nurses',
      cred1Body: 'Every nurse is a member of the OIIQ, Quebec’s nursing regulator.',
      cred2Title: 'Protected data',
      cred2Body: 'Records hosted in Canada, encrypted and built to meet Quebec’s Law 25.',
      cred3Title: 'Liability insurance',
      cred3Body: 'Our nurses carry professional liability insurance.',
      cred4Title: 'Itemized receipts',
      cred4Body: 'Itemized receipt after every visit; reimbursement depends on your plan.',

      dispatchEyebrow: 'Live dispatch',
      dispatchTitle1: 'Three texts.',
      dispatchTitle2: 'Zero phone calls.',
      dispatchBody: 'No four-hour window. You know who is coming, when she leaves, and her estimated arrival. Greater Montreal at launch; zones and hours confirmed in the app.',
      dispatchNote: 'Fast matching with OIIQ-member nurses.',
      dispatchSms1Time: '2:03 PM',
      dispatchSms1: 'Request confirmed. Camille, OIIQ-licensed nurse, will be at your door around 2:40 PM.',
      dispatchSms2Time: '2:31 PM',
      dispatchSms2: 'Camille just left. Reply to this message if you have any instructions for her.',
      dispatchSms3Time: '2:36 PM',
      dispatchSms3: 'Camille arrives in about 5 minutes.',
      dispatchThreadLabel: 'Example of texts received during a visit',

      servicesEyebrow: 'Care offered',
      servicesTitle: 'What a nurse can do in your home.',
      servicesNote: 'Some services may be eligible for reimbursement by your private insurance, depending on your plan. An itemized receipt is provided after every visit.',
      patientsEyebrow: 'Our patients',
      patientsTitle1: 'Care comes to the people',
      patientsTitle2: 'who can no longer',
      patientsTitle3: 'travel to get it.',
      patientsBody: 'Seniors losing independence, convalescing patients, families without a car, caregivers at the end of their rope. For them, a clinic appointment costs half a day — and sometimes adapted transport.',
      nursesEyebrow: 'For nurses',
      nursesPitch: 'Choose your shifts, your areas and the care you want to give.',
      nursesCta: 'Join the network',

      ctaTitle1: 'We\'re launching soon',
      ctaTitle2: 'in Quebec.',
      ctaBody: 'Sign up to be notified first when we launch in your area.',
      ctaButton: 'Sign me up',
      ctaFinePrint: 'No card required. Unsubscribe anytime.',
    },
    header: {
      home: 'Home',
      language: 'Language',
      joinWaitlist: 'Join the waitlist',
      about: 'About',
      howItWorks: 'How it works',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Download the app',
      recruitment: 'Recruitment',
      contact: 'Contact',
    },
    hero: {
      availableInQuebec: 'Available in Quebec',
      title: 'A nurse at your door,',
      titleHighlight: 'no waiting room.',
      subtitle: 'OIIQ-member nurses, booked in a few clicks. Professional and secure.',
      subtitleShort: 'Licensed nurses, booked in a few taps.',
      bookNow: 'Join the waitlist',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Waitlist',
      waitlistSubtitle: 'Be the first to know and get',
      waitlistDiscount: '20% off',
      waitlistDiscountSuffix: 'at launch.',
      emailPlaceholder: 'your@email.com',
      successMessage: 'Registered!',
      errorMessage: 'Error',
      invalidEmail: 'Invalid email',
      personsRegistered: 'People registered',
      patientsServed: 'Patients served',
      nextAppointment: 'Next appointment',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Network',
      nurses: 'Nurses',
      zone: 'Zone',
      quebec: 'Greater Montreal',
      continueButton: 'Continue',
      or: 'OR',
      continueWithApple: 'Continue with Apple',
      continueWithGoogle: 'Continue with Google',
      continueWithEmail: 'Continue with email',
      findAccount: 'Find your account',
      phoneNumber: 'Phone number',
      getStarted: 'Get started with MobiSoins',
    },
    howItWorks: {
      title: 'How does it work?',
      subtitle: 'MobiSoins simplifies access to home care.',
      step1Title: 'Book in a few clicks',
      step1Description: 'Choose your service and a time that suits you, then confirm your address. We find available nurses near you.',
      step2Title: 'Matching & real-time tracking',
      step2Description: 'We match you with a nurse suited to your needs. Track their trip to you on the map in real time.',
      step3Title: 'Professional home care',
      step3Description: 'Receive quality care in the comfort of your home. Clinical report available in the app after every visit.',
      step1: {
        title: 'Book in a few clicks',
        description: 'Choose your service and a time that suits you, then confirm your address. We find available nurses near you.',
      },
      step2: {
        title: 'Matching & real-time tracking',
        description: 'We match you with a nurse suited to your needs. Track their trip to you on the map in real time.',
      },
      step3: {
        title: 'Professional home care',
        description: 'Receive quality care in the comfort of your home. Clinical report available in the app after every visit.',
      },
    },
    services: {
      badge: 'Our advantages',
      seeAll: 'View all services',
      mainTitle: 'Your health deserves',
      mainTitlePrefix: 'complete',
      mainTitleHighlight: 'services',
      mainTitleSuffix: ' ',
      card1Visual: 'Dashboard',
      card1Item1: 'Next appointment',
      card1Item1Detail: 'Tomorrow, 2:00 PM',
      card1Item2: 'Medications',
      card1Item2Detail: 'Taken at 8:00 AM',
      card1Badge: 'Personalized tracking',
      card1Title: 'Everything in one place',
      card1Description: 'Manage your appointments, track your prescriptions, and view your care history at a glance.',
      card1Point1: 'Appointment & medication reminders',
      card1Point2: 'Complete care history in the app',
      card1Point3: 'Shareable digital clinical reports',
      card2Visual: 'Smart search',
      card2Badge: 'Precise matching',
      card2Title: 'Find the ideal expert',
      card2Description: 'We connect you with a qualified nurse near you.',
      card2Point1: 'OIIQ-member nurses',
      card2Point2: 'Fast matching',
      card2Point3: 'Time slots that fit your schedule',
      card3Visual: 'Your data',
      card3Badge: 'Clinical tracking',
      card3Title: 'Follow your care history',
      card3Description: 'The app will let you follow your care history and share your reports.',
      card3Point1: 'Blood draws, wound care & injections',
      card3Point2: 'Post-op, senior & pediatric care',
      card3Point3: 'Real-time visit & vitals tracking',
      mapBadge: 'Launching in Greater Montreal',
      bannerTitle: 'Home care, starting',
      bannerTitleHighlight: 'in Greater Montreal.',
      bannerDescription: 'OIIQ-licensed nurses, first in the Greater Montreal area, then in more regions of Quebec as we grow.',
      bannerCta: 'Join the waitlist',
    },
    patients: {
      titleStart: 'Care that makes people',
      titleItalic: 'smile.',
      caption1: 'Home visit · Rosemont',
      caption2: 'Vaccination · Laval',
      imageAlt1: 'A MobiSoins nurse visiting a family at home',
      imageAlt2: 'A MobiSoins nurse vaccinating a child',
      badge: 'Our patients',
      title: 'Care that makes people smile',
      subtitle: 'Every day, our nurses bring professional, compassionate care directly to our patients\' homes.',
      description: 'Blood tests, post-operative follow-up, medication administration, wound care or simply a reassuring presence: MobiSoins supports every patient with professionalism and compassion, at every step of their recovery. Our OIIQ-licensed nurses travel throughout the Greater Montreal area to deliver quality care, without the stress or the commute.',
      point1Title: 'Personalized care',
      point1Desc: 'Every care plan is tailored to the patient\'s exact needs, in the comfort of home.',
      point2Title: 'Zero travel',
      point2Desc: 'No more long clinic waits. The nurse comes straight to your door.',
      point3Title: 'Full clinical follow-up',
      point3Desc: 'A detailed report after every visit, shared with the patient and their loved ones.',
      point4Title: 'Compassionate support',
      point4Desc: 'Our nurses take the time to listen, explain and reassure.',
    },
    location: {
      name: 'Montreal, Quebec',
      caption: 'Launching in Montreal · Greater Montreal first',
      eyebrow: 'Coverage',
      titleStart: 'Montreal first,',
      titleItalic: 'then across Quebec.',
      lede: 'We\'re opening the app in Greater Montreal first. Leave your city on the waitlist, and we\'ll message you the day booking opens near you.',
      row1Label: 'Launching',
      row1Value: 'Montreal · Laval · Longueuil',
      row2Label: 'Waitlist',
      row2Value: 'Quebec City · Gatineau · Sherbrooke',
      cta: 'Add my city',
    },
    map: {
      titleStart: 'Home care',
      titleItalic: 'in just minutes.',
      label1: 'Matching',
      label2: 'Nurses',
      label3: 'Tracking',
      eta: 'ETA 8 min',
      imageAlt: 'A MobiSoins nurse driving to a patient\'s home',
      badge: 'Real-time dispatch',
      title: 'Home care, quickly',
      description: 'We match each patient with an available OIIQ-member nurse nearby.',
      bullet1: 'Fast, automatic matching',
      bullet1Sub: 'We find an available nurse near you.',
      bullet2: 'OIIQ-member nurses',
      bullet2Sub: 'Every professional is checked against the Order\'s register.',
      bullet3: 'Real-time GPS tracking',
      bullet3Sub: 'Follow your nurse\'s journey right to your door.',
      footnote: 'Launching in Greater Montreal',
      stepBooked: 'Booked',
      stepMatched: 'Matched',
      stepEnRoute: 'En route',
      stepArrived: 'Arrived',
      trackTitle: 'Visit tracking',
    },
    blog: {
      badge: 'Our blog',
      title: 'Latest articles',
      subtitle: 'Stay informed about the latest health news, expert advice, and MobiSoins innovations.',
      readMore: 'Read article',
      readTime: 'read',
      article1Tag1: 'Health innovation',
      article1Tag2: 'Telehealth',
      article1Title: 'How telehealth is transforming medical monitoring',
      article1Description: 'What if consulting a healthcare professional were as simple as a video call? Telehealth is fundamentally transforming medical monitoring.',
      article2Tag1: 'Practical guide',
      article2Tag2: 'Home',
      article2Title: 'How to prepare for your first visit with MobiSoins',
      article2Description: 'Receiving home nursing care means benefiting from professional follow-up directly in your own environment.',
      article3Tag1: 'Health trend',
      article3Tag2: 'Seniors',
      article3Title: 'The benefits of home care for seniors',
      article3Description: 'What if the best place to age wasn\'t the hospital... but simply at home?',
    },
    faq: {
      title: 'Frequently asked questions',
      subtitle: 'Find answers to your most common questions',
      ctaPrompt: 'Have a question? Check out our frequently asked questions.',
      ctaButton: 'View FAQ',
      searchPlaceholder: 'Search for a question...',
      noResults: 'No questions found for your search.',
      question1: 'How does MobiSoins work?',
      answer1: 'MobiSoins connects patients with OIIQ-licensed nurses for home care. You book in the app, track your nurse in real time, and pay securely once the visit is done.',
      question2: 'Are the nurses really qualified?',
      answer2: 'Yes. All our nurses are members of the Ordre des infirmières et infirmiers du Québec (OIIQ) and carry professional liability insurance.',
      question3: 'What are the costs?',
      answer3: 'Prices vary by service. The exact price is shown before you book, with no hidden fees. Secure payment by credit card or Apple Pay.',
      question4: 'Which regions are covered?',
      answer4: 'We\'re launching first in the Greater Montreal area, with the goal of expanding to other regions of Quebec. Add your city to the waitlist to be notified when booking opens near you.',
      question5: 'How do I become a partner nurse?',
      answer5: 'Join the waitlist as a nurse. We verify your OIIQ license and insurance, then meet you for an interview before your first visits.',
      question6: 'Are payments secure?',
      answer6: 'Yes. All payments are processed by a secure payment provider, and we never store your banking information.',
      question7: 'Can I choose my nurse?',
      answer7: 'You can view your nurse\'s profile, ratings and experience before confirming the visit. If you have a preference, you can request the same nurse for future visits.',
      question8: 'What happens in case of a medical emergency?',
      answer8: 'MobiSoins is NOT an emergency service. In a life-threatening emergency, call 911. Our nurses can handle non-urgent care and direct you to the emergency room if necessary.',
    },
    contact: {
      title: 'Contact us',
      description: 'Here for your questions, feedback or partnership opportunities. We\'ll get back to you as soon as we can.',
      detailsTitle: 'Contact details',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      web: 'Web',
      firstName: 'First name',
      firstNamePlaceholder: 'First name',
      lastName: 'Last name',
      lastNamePlaceholder: 'Last name',
      emailLabel: 'Email',
      emailPlaceholder: 'your@email.com',
      subject: 'Subject',
      subjectPlaceholder: 'How can we help you?',
      message: 'Message',
      messagePlaceholder: 'Describe your request in detail...',
      send: 'Send message',
      sending: 'Sending...',
      sent: '✓ Message sent!',
      sentConfirm: 'Thank you! We\'ll get back to you as soon as we can.',
      errorGeneric: 'Something went wrong. Please try again or email us at info@mobisoins.com.',
      errorConfig: 'The form isn\'t configured yet. Please email us at info@mobisoins.com.',
    },
    stats: {
      patients: 'Patients served',
      nurses: 'OIIQ nurses',
      satisfaction: 'Satisfaction',
      availability: 'Availability',
      cities: 'Cities in Quebec',
    },
    newsletter: {
      title: 'Join the waitlist',
      subtitle: 'Get started today.',
      cta: 'Sign up now',
      description: 'Be the first to know when MobiSoins launches in your area.',
      emailPlaceholder: 'your@email.com',
      submitButton: 'Sign up',
      submitting: 'Sending...',
      successTitle: 'Thank you!',
      successMessage: 'You\'re on the waitlist.',
      errorTitle: 'Error',
      errorMessage: 'An error occurred. Please try again.',
      invalidEmailTitle: 'Invalid email',
      priorityAccess: 'Priority access',
      noCardRequired: 'No card required',
    },
    visit: {
      eyebrow: 'A visit, minute by minute',
      titleStart: 'What a Tuesday afternoon',
      titleItalic: 'looks like.',
      lede: 'A blood draw for a 74-year-old patient in Rosemont, booked by her daughter from the office.',
      step1Title: 'Booked',
      step1Text: 'Blood draw, today, between 2:30 and 4:00 PM. Price confirmed on screen.',
      step2Title: 'Nurse matched',
      step2Text: 'Marie-Ève accepts. Her profile, rating and ETA appear in the app.',
      step3Title: 'At the door',
      step3Text: 'Her daughter gets a notification at work. The visit takes about 20 minutes.',
      step4Title: 'Report in the app',
      step4Text: 'Clinical note shared with the family and the treating physician. Receipt sent for insurance.',
      caption: 'Visit in progress',
      imageAlt: 'A MobiSoins nurse applying a dressing to an older woman\'s arm in her living room',
    },
    waitlist: {
      eyebrow: 'Waitlist',
      titleStart: 'Be first in line when the app opens',
      titleItalic: 'in your city.',
      lede: 'Leave your email, and we\'ll send one message when booking goes live near you — nothing else.',
      social: 'Patients and nurses already on the list',
      firstName: 'First name',
      firstNamePlaceholder: 'Nathalie',
      city: 'City',
      otherCity: 'Another city',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      role: 'I\'m signing up as',
      rolePatient: 'Patient or family member',
      roleNurse: 'Nurse (OIIQ member)',
      roleEmployer: 'Employer or clinic',
      submit: 'Join the waitlist',
      done: 'You\'re on the list',
      note: 'One email at launch. Unsubscribe any time.',
      error: 'Something went wrong. Please try again.',
    },
    about: {
      badge: 'About',
      title: 'About us',
      missionBadge: 'Our mission',
      missionTitle: 'Accessible care, wherever you are in Greater Montreal.',
      missionLead: 'In Quebec, getting simple care can mean hours of waiting, sometimes days. MobiSoins exists to change that. We bring clinical expertise directly to patients\' homes, quickly and safely.',
      statementBadge: 'Our commitment',
      statement1: 'MobiSoins\' mission is to make quality healthcare more accessible by delivering safe, professional and compassionate care directly to patients\' homes through an innovative digital platform.',
      statement2: 'We believe that no one should have to wait hours in a crowded clinic, or travel across the city, to receive care that can just as easily be provided where they live. By connecting patients with OIIQ-licensed nurses in just a few minutes, MobiSoins removes the distance between a person and the care they need, whether it is a blood test, a wound dressing, a chronic-condition follow-up or a reassuring visit for a loved one.',
      statement3: 'Behind every visit stands a team that pairs clinical expertise with modern technology. Our nurses uphold the highest standards of practice, and our platform keeps every step transparent, from booking to the clinical report shared after the visit. This is how we build trust, one home and one patient at a time, across Quebec.',
      problemBadge: 'The problem',
      problemTitle: 'A system under pressure, patients left behind.',
      problemText1: 'Emergency rooms are overflowing, waitlists keep growing, and an aging population needs care more and more often. For a simple dressing change, a blood test or a follow-up, thousands of people travel, wait and lose precious time.',
      problemText2: 'Meanwhile, highly qualified nurses lack modern tools to efficiently reach the patients who need them. The talent exists. The demand exists. What was missing was the connection between the two.',
      problemText3: 'That is exactly the gap MobiSoins was founded to close, in Montreal in 2025, by a team bringing together more than 36 years of combined nursing experience and engineers from major tech companies like Microsoft, IBM and Constellation Software.',
      storyBadge: 'Our story',
      storyTitle: 'It started with a two-day wait.',
      storyText1: 'In September 2025, in Montreal, one of our founders watched his mother spend two full days in a hospital. Not for surgery, not for anything complex. She was waiting for a Tylenol and a doctor\'s note. Two days, for something that should have taken minutes. That wait was the spark for MobiSoins.',
      storyText2: 'Four people who had seen this problem from both sides decided to fix it. Two clinical nurses with more than 36 years of combined experience at the bedside, and two software engineers who had built large-scale systems at Microsoft, IBM and Constellation Software. They met through mutual connections, shared the same frustration, and founded MobiSoins together as equals.',
      storyText3: 'The problem runs two ways. Patients wait far too long for care that could easily come to them, and the nurses who provide that care are too often undervalued and underpaid for their expertise. MobiSoins was built to fix both. We bring safe, professional and compassionate care to patients of every age, and we give nurses a better, fairer way to practice.',
      storyText4: 'We are starting in Quebec, but our ambition does not stop there. Our goal is to expand across the country and then around the world, so that anyone, anywhere, can receive quality healthcare in the comfort of their own home.',
      storyQuote: 'No one should wait two days for a Tylenol.',
      foundersLabel: 'The founders',
      founderRole: 'Co-founder',
      foundersTitle: 'Four people, two sides of the same problem.',
      foundersLead: 'Two clinical nurses and two software engineers, brought together by the same frustration and partnered as equals.',
      founderFrom: 'From',
      founderPrev: 'Previously',
      founderPhotoPending: 'Portrait coming soon',
      ctaTitle: 'Want care at home?',
      ctaBody: 'Join the waitlist and be notified when we launch in your area.',
      ctaButton: 'Join the waitlist',
      fact1Value: '36+',
      fact1Label: 'Years of combined nursing experience',
      fact2Value: '2025',
      fact2Label: 'Founded in Montreal, Quebec',
      fact3Value: 'Big tech',
      fact3Label: 'Engineering from Microsoft, IBM and Constellation',
      teamBadge: 'Our team',
      teamTitle: 'Care and technology, side by side.',
      teamLead: 'You cannot improve healthcare without bringing together the people who deliver care and the people who build the tools. That is why our nurses and engineers work on the same team, toward the same goal.',
      team1Title: 'Clinical rigor',
      team1Desc: 'OIIQ-licensed nurses define every care protocol and validate every feature before it ever reaches a patient.',
      team2Title: 'Serious engineering',
      team2Desc: 'A technical team builds a fast, reliable and secure platform, from real-time matching to the clinical record.',
      team3Title: 'On the ground',
      team3Desc: 'Our operations stay close to patients and nurses to keep improving the service, one visit at a time.',
      valuesBadge: 'Our values',
      valuesTitle: 'What guides us',
      value1Title: 'Accessibility',
      value1Desc: 'Quality care for everyone, everywhere in Quebec, without the long waits.',
      value2Title: 'Humanity',
      value2Desc: 'The person at the heart of every visit, with genuine listening and compassion.',
      value3Title: 'Clinical excellence',
      value3Desc: 'OIIQ-licensed nurses held to the highest standards of practice.',
      value4Title: 'Innovation',
      value4Desc: 'Technology in service of faster, safer, more transparent care.',
      description1: 'MobiSoins is a mobile clinic offering professional nursing care at home and online.',
      description2: 'Founded by two clinical nurses, MobiSoins has a mission: to make healthcare more accessible, faster and safer, while placing the person at the heart of every intervention.',
      description3: 'Through a modern approach combining clinical expertise and innovation, we offer services tailored to the needs of the population, in accordance with the highest standards of practice.',
      servicesTitle: 'Services',
      servicesIntro: 'MobiSoins offers a complete range of nursing care tailored to your needs, at home or online.',
      insuranceNote: 'Some services may be eligible, depending on your plan, for reimbursement by private insurance. Official receipts provided.',
      service1Title: 'Nursing care',
      service1Desc: 'Wound dressing, suture removal, medication administration, post-operative care and clinical follow-up.',
      service2Title: 'Chronic disease management',
      service2Desc: 'Monitoring of diabetes, hypertension and other conditions, with education and complication prevention.',
      service3Title: 'Health assessment',
      service3Desc: 'Complete evaluation, vital signs monitoring and personalized health advice.',
      service4Title: 'Sexual health',
      service4Desc: 'STI screening, contraception, education and follow-up.',
      service5Title: 'Senior care',
      service5Desc: 'Health monitoring, medication management and home support.',
      service6Title: 'Lab tests & samples',
      service6Desc: 'Blood draws and diagnostic tests, with a prescription.',
      service7Title: 'Corporate services',
      service7Desc: 'Mobile clinics, health assessments and workplace prevention programs.',
    },
    logoCloud: {
      title: 'Trusted partners in Quebec',
    },
    footer: {
      product: 'Product',
      howItWorks: 'How it works',
      articles: 'Articles',
      faq: 'FAQ',
      social: 'Social',
      madeIn: 'Made with care in Quebec',
      description: 'A home-care nursing platform for the Greater Montreal area. We match OIIQ-licensed nurses with patients quickly.',
      company: 'Company',
      aboutUs: 'About us',
      press: 'Press',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'For patients',
      forNurses: 'For nurses',
      pricing: 'Pricing',
      insurance: 'Insurance',
      support: 'Support',
      helpCenter: 'Help center',
      contact: 'Contact',
      privacy: 'Privacy',
      terms: 'Terms',
      legal: 'Legal',
      privacyPolicy: 'Privacy policy',
      termsOfService: 'Terms of use',
      cookies: 'Cookie policy',
      allRightsReserved: 'All rights reserved.',
    },
  },
};



