'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'FR' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Always start at 'FR' so the server render and the first client render match
  // (avoids a hydration mismatch). Browser/stored preference is applied after mount.
  const [language, setLanguageState] = useState<Language>('FR');

  useEffect(() => {
    const stored = localStorage.getItem('language');
    if (stored === 'FR' || stored === 'EN') {
      setLanguageState(stored);
    } else if (!navigator.language.startsWith('fr')) {
      setLanguageState('EN');
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  FR: {
    // Copy for the product-led landing redesign (desktop first). Kept in its own
    // `v2` block so the legacy section keys other pages still use stay untouched.
    v2: {
      heroBadge: 'Infirmières autorisées OIIQ · Québec',
      heroCtaPrimary: 'Rejoindre la liste d\'attente',
      heroCtaSecondary: 'Voir comment ça marche',

      stepsTitle: 'Trois étapes, aucune salle d\'attente.',
      stepsEyebrow: 'Comment ça marche',
      step1Num: '01', step1Meta: '2 minutes', step1Title: 'Décrivez le soin',
      step1Opt1: 'Prise de sang', step1Opt2: 'Pansement / plaie', step1Opt3: 'Injection / vaccin',
      step1FootLabel: 'Aujourd\'hui', step1FootValue: '14 h 30',
      step2Num: '02', step2Meta: 'Moins de 60 s', step2Title: 'On trouve l\'infirmière',
      step2Chip: 'En route · 8 min', step2Licence: 'Autorisée OIIQ',
      step3Num: '03', step3Meta: 'Après la visite', step3Title: 'Le soin, puis le rapport',
      step3Row1: 'Tension', step3Row2: 'Prélèvement',
      step3Row3: 'Transmis au médecin', step3Row3Value: 'Oui',
      step3Row4: 'Reçu d\'assurance', step3Row4Value: 'PDF',
      step3Cta: 'Télécharger',

      cred1Title: 'Infirmières autorisées',
      cred1Body: 'Permis OIIQ vérifié avant la première visite.',
      cred2Title: 'Données au Québec',
      cred2Body: 'Dossiers hébergés et chiffrés, conformes à la Loi 25.',
      cred3Title: 'Assurance responsabilité',
      cred3Body: 'Chaque visite est couverte, sans démarche de votre part.',
      cred4Title: 'Reçus pour assurance',
      cred4Body: 'Reçu admissible émis automatiquement après chaque soin.',

      dispatchEyebrow: 'Répartition en direct',
      dispatchTitle1: 'Vous savez où elle est,',
      dispatchTitle2: 'à la minute près.',
      dispatchBody: 'Pas d\'appel, pas de fenêtre de quatre heures. Une alerte cinq minutes avant qu\'elle sonne.',
      dispatchRow1: 'Jumelage', dispatchRow1Value: 'moins de 60 s',
      dispatchRow2: 'Couverture', dispatchRow2Value: 'Grand Montréal',
      dispatchRow3: 'Disponibilité', dispatchRow3Value: '7 jours sur 7',
      dispatchEtaLabel: 'Arrivée estimée', dispatchEta: '8 min',
      dispatchNurseStatus: 'Autorisée OIIQ · en route',
      dispatchMessage: 'Message',

      servicesEyebrow: 'Soins offerts',
      servicesTitle: 'Ce qu\'une infirmière peut faire chez vous.',
      servicesNote: 'Certains soins sont admissibles au remboursement par assurances privées. Reçu officiel fourni après chaque visite.',
      patientsEyebrow: 'Nos patients',
      patientsTitle1: 'Les soins viennent',
      patientsTitle2: 'à ceux qui ne peuvent',
      patientsTitle3: 'plus se déplacer.',
      patientsBody: 'Aînés en perte d\'autonomie, patients en convalescence, familles sans voiture, proches aidants à bout de souffle. Pour eux, un rendez-vous en clinique coûte une demi-journée — et parfois un transport adapté.',
      nursesEyebrow: 'Pour les infirmières',
      nursesPitch: 'Choisissez vos quarts, vos secteurs et vos types de soins.',
      nursesCta: 'Rejoindre le réseau',

      ctaTitle1: 'Nous lançons bientôt',
      ctaTitle2: 'au Québec.',
      ctaBody: 'Inscrivez-vous pour être parmi les premiers servis dans votre secteur.',
      ctaButton: 'M\'inscrire',
      ctaFinePrint: 'Aucune carte requise. Désabonnement en un clic.',
    },
    header: {
      home: 'Accueil',
      language: 'Langue',
      joinWaitlist: 'Liste d\'attente',
      about: 'À propos',
      howItWorks: 'Comment ça marche',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Télécharger l\'App',
      recruitment: 'Recrutement',
      contact: 'Contact',
    },
    hero: {
      availableInQuebec: 'Disponible au Québec',
      title: 'Une infirmière chez vous',
      titleHighlight: 'en quelques minutes',
      subtitle: 'Des infirmières autorisées, réservées en quelques clics. Professionnel, sécurisé, disponible 24/7.',
      subtitleShort: 'Des infirmières autorisées, réservées en quelques clics.',
      bookNow: 'Rejoindre la liste d\'attente',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Liste d\'Attente',
      waitlistSubtitle: 'Soyez le premier averti et obtenez',
      waitlistDiscount: '20% de rabais',
      waitlistDiscountSuffix: 'au lancement.',
      emailPlaceholder: 'votre@email.com',
      successMessage: 'Inscrit !',
      errorMessage: 'Erreur',
      invalidEmail: 'Email invalide',
      personsRegistered: 'Personnes inscrites',
      patientsServed: 'Patients Traités',
      nextAppointment: 'Prochain Soin',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Réseau',
      nurses: 'Inf.',
      zone: 'Zone',
      quebec: 'Québec',
      continueButton: 'Continuer',
      or: 'OU',
      continueWithApple: 'Continuer avec Apple',
      continueWithGoogle: 'Continuer avec Google',
      continueWithEmail: 'Continuer avec une adresse e-mail',
      findAccount: 'Retrouver votre compte',
      phoneNumber: 'Numéro de téléphone',
      getStarted: 'C\'est parti avec MobiSoins',
    },
    howItWorks: {
      title: 'Comment ça marche?',
      subtitle: 'MobiSoins simplifie l\'accès aux soins de santé à domicile.',
      step1Title: 'Réservez en 2 Minutes',
      step1Description: 'Choisissez votre service, l\'heure qui vous convient, et confirmez votre adresse. Notre IA trouve immédiatement les infirmières disponibles près de vous.',
      step2Title: 'Matching & Suivi en Temps Réel',
      step2Description: 'Notre algorithme sélectionne l\'infirmière la plus adaptée. Suivez son déplacement vers vous sur la carte en temps réel.',
      step3Title: 'Soins Professionnels à Domicile',
      step3Description: 'Profitez de soins de qualité hospitalière dans le confort de votre maison. Rapport clinique disponible dans l\'application après chaque visite.',
      step1: {
        title: 'Réservez en 2 Minutes',
        description: 'Choisissez votre service, l\'heure qui vous convient, et confirmez votre adresse. Notre IA trouve immédiatement les infirmières disponibles près de vous.',
      },
      step2: {
        title: 'Matching & Suivi en Temps Réel',
        description: 'Notre algorithme sélectionne l\'infirmière la plus adaptée. Suivez son déplacement vers vous sur la carte en temps réel.',
      },
      step3: {
        title: 'Soins Professionnels à Domicile',
        description: 'Profitez de soins de qualité hospitalière dans le confort de votre maison. Rapport clinique disponible dans l\'application après chaque visite.',
      },
    },
    services: {
      badge: 'Nos Avantages',
      seeAll: 'Voir tous nos services',
      mainTitle: 'Votre santé mérite',
      mainTitlePrefix: 'des',
      mainTitleHighlight: 'services',
      mainTitleSuffix: 'complets',
      card1Visual: 'Tableau de Bord',
      card1Item1: 'Prochain RDV',
      card1Item1Detail: 'Demain, 14:00',
      card1Item2: 'Médicaments',
      card1Item2Detail: 'Pris à 08:00',
      card1Badge: 'Suivi Personnalisé',
      card1Title: 'Tout au même endroit',
      card1Description: 'Gérez vos rendez-vous, suivez vos prescriptions et consultez votre historique de soins en un clin d\'œil.',
      card1Point1: 'Rappels de rendez-vous et de médicaments',
      card1Point2: 'Historique de soins complet dans l\'application',
      card1Point3: 'Rapports cliniques numériques partageables',
      card2Visual: 'Recherche Intelligente',
      card2Badge: 'Matching Précis',
      card2Title: 'Trouvez l\'Expert Idéal',
      card2Description: 'Notre algorithme vous connecte instantanément avec l\'infirmière qualifiée la plus proche de chez vous.',
      card2Point1: 'Infirmières certifiées OIIQ et vérifiées',
      card2Point2: 'Jumelage par IA en quelques secondes',
      card2Point3: 'Disponibilité le jour même, 24/7',
      card3Visual: 'Vos Données',
      card3Badge: 'Suivi Clinique',
      card3Title: 'Visualisez vos progrès',
      card3Description: 'Des graphiques clairs et détaillés pour suivre l\'évolution de votre santé et partager vos rapports facilement.',
      card3Point1: 'Prises de sang, soins de plaies et injections',
      card3Point2: 'Soins post-opératoires, aînés et pédiatriques',
      card3Point3: 'Suivi des visites et des signes vitaux en temps réel',
      mapBadge: 'Disponible à travers le Québec',
      bannerTitle: 'Soins à domicile partout',
      bannerTitleHighlight: 'au Québec.',
      bannerDescription: 'Infirmières certifiées OIIQ disponibles à Montréal, Québec, Laval, Longueuil, Sherbrooke, Gatineau et partout en province.',
      bannerCta: 'Rejoindre la liste d\'attente',
    },
    patients: {
      badge: 'Nos patients',
      title: 'Des soins qui font sourire',
      subtitle: 'Chaque jour, nos infirmières apportent des soins professionnels et humains directement au domicile de nos patients.',
      description: 'Prise de sang, suivi post-opératoire, administration de médicaments, soins de plaies ou simplement une présence rassurante : MobiSoins accompagne chaque patient avec professionnalisme et bienveillance, à chaque étape de son rétablissement. Nos infirmières certifiées OIIQ se déplacent partout au Québec pour offrir des soins de qualité hospitalière, sans le stress ni les déplacements.',
      point1Title: 'Soins personnalisés',
      point1Desc: 'Chaque plan de soins est adapté aux besoins précis du patient, dans le confort de son domicile.',
      point2Title: 'Zéro déplacement',
      point2Desc: 'Fini les longues attentes en clinique. L\'infirmière se déplace directement chez vous.',
      point3Title: 'Suivi clinique complet',
      point3Desc: 'Un rapport détaillé après chaque visite, partagé avec le patient et ses proches.',
      point4Title: 'Accompagnement humain',
      point4Desc: 'Nos infirmières prennent le temps d\'écouter, d\'expliquer et de rassurer.',
    },
    map: {
      badge: 'Dispatch en temps réel',
      title: 'Des soins à domicile en quelques minutes',
      description: 'Notre algorithme de dispatch connecte automatiquement chaque patient à l\'infirmière disponible la plus proche, certifiée OIIQ.',
      bullet1: 'Matching en moins de 60 secondes',
      bullet1Sub: 'Nous trouvons l\'infirmière disponible la plus proche instantanément.',
      bullet2: 'Infirmières certifiées OIIQ vérifiées',
      bullet2Sub: 'Chaque professionnelle est validée et certifiée par l\'Ordre.',
      bullet3: 'Suivi GPS en temps réel',
      bullet3Sub: 'Suivez le déplacement de votre infirmière jusqu\'à votre porte.',
      footnote: 'Disponible partout au Québec',
      stepBooked: 'Réservé',
      stepMatched: 'Jumelé',
      stepEnRoute: 'En route',
      stepArrived: 'Arrivé',
      trackTitle: 'Suivi de la visite',
    },
    blog: {
      badge: 'Notre Blog',
      title: 'Derniers Articles',
      subtitle: 'Restez informé sur les dernières actualités en santé, les conseils de nos experts et les innovations MobiSoins.',
      readMore: 'Lire l\'article',
      readTime: 'lecture',
      article1Tag1: 'Innovation santé',
      article1Tag2: 'Télésanté',
      article1Title: 'Comment la télésanté transforme le suivi médical',
      article1Description: 'Et si consulter un professionnel de santé devenait aussi simple qu\'un appel vidéo ? La télésanté transforme le suivi médical en profondeur.',
      article2Tag1: 'Guide pratique',
      article2Tag2: 'Domicile',
      article2Title: 'Comment bien se préparer à sa première visite avec MobiSoins',
      article2Description: 'Recevoir des soins infirmiers à domicile, c\'est bénéficier d\'un suivi professionnel directement dans son environnement.',
      article3Tag1: 'Tendance santé',
      article3Tag2: 'Aînés',
      article3Title: 'Les avantages des soins à domicile pour les aînés',
      article3Description: 'Et si la meilleure place pour vieillir n\'était pas l\'hôpital… mais tout simplement chez soi ?',
    },
    faq: {
      title: 'Questions Fréquentes',
      subtitle: 'Trouvez des réponses à vos questions les plus courantes',
      ctaPrompt: 'Une question ? Consultez notre foire aux questions.',
      ctaButton: 'Voir la FAQ',
      searchPlaceholder: 'Rechercher une question...',
      noResults: 'Aucune question trouvée pour votre recherche.',
      question1: 'Comment fonctionne MobiSoins?',
      answer1: 'MobiSoins connecte les patients avec des infirmières certifiées pour des soins à domicile. Vous réservez via l\'application, suivez votre infirmière en temps réel, et payez de manière sécurisée après le service.',
      question2: 'Les infirmières sont-elles vraiment certifiées?',
      answer2: 'Oui, absolument. Toutes nos infirmières sont membres de l\'Ordre des Infirmières et Infirmiers du Québec (OIIQ), possèdent une assurance responsabilité civile, et ont passé notre processus de vérification rigoureux incluant la vérification des antécédents.',
      question3: 'Quels sont les coûts?',
      answer3: 'Les prix varient selon le service (45$ à 95$ en moyenne). Le prix exact est affiché avant la réservation. Aucun frais caché. Paiement sécurisé par carte de crédit ou Apple Pay.',
      question4: 'Quelles régions sont couvertes?',
      answer4: 'Actuellement disponible à Montréal, Québec, Laval, Gatineau, Longueuil, et Sherbrooke. Expansion prévue dans 10+ villes d\'ici fin 2027.',
      question5: 'Comment devenir infirmière partenaire?',
      answer5: 'Inscrivez-vous via notre formulaire \'Devenir Infirmière\'. Nous vérifions votre licence OIIQ, assurance, et effectuons une entrevue. Vous pouvez commencer à accepter des missions sous 5 jours ouvrables.',
      question6: 'Les paiements sont-ils sécurisés?',
      answer6: 'Oui, tous les paiements sont traités par Stripe, leader mondial en sécurité des paiements. Nous ne stockons jamais vos informations bancaires.',
      question7: 'Puis-je choisir mon infirmière?',
      answer7: 'Vous pouvez voir le profil, les évaluations, et l\'expérience de l\'infirmière avant d\'accepter la mission. Si vous avez une préférence, vous pouvez la demander pour vos prochaines visites.',
      question8: 'Que se passe-t-il en cas d\'urgence médicale?',
      answer8: 'MobiSoins n\'est PAS un service d\'urgence. En cas d\'urgence vitale, composez le 911. Nos infirmières peuvent gérer les soins non-urgents et vous orienter vers les urgences si nécessaire.',
    },
    contact: {
      title: 'Contactez-nous',
      description: 'Disponibles pour répondre à vos questions, collaborations ou partenariats. Nous vous répondons sous 24h.',
      detailsTitle: 'Coordonnées',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'Courriel',
      web: 'Web',
      firstName: 'Prénom',
      firstNamePlaceholder: 'Prénom',
      lastName: 'Nom',
      lastNamePlaceholder: 'Nom',
      emailLabel: 'Courriel',
      emailPlaceholder: 'votre@courriel.com',
      subject: 'Sujet',
      subjectPlaceholder: 'Comment pouvons-nous vous aider ?',
      message: 'Message',
      messagePlaceholder: 'Décrivez votre demande en détail...',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      sent: '✓ Message envoyé !',
      sentConfirm: 'Merci ! Nous vous répondrons dans les 24h.',
      errorGeneric: 'Une erreur est survenue. Veuillez réessayer ou nous écrire à info@mobisoins.com.',
      errorConfig: 'Le formulaire n\'est pas encore configuré. Écrivez-nous à info@mobisoins.com.',
    },
    stats: {
      patients: 'Patients servis',
      nurses: 'Infirmières OIIQ',
      satisfaction: 'Satisfaction',
      availability: 'Disponibilité',
      cities: 'Villes au Québec',
    },
    newsletter: {
      title: 'Rejoignez la liste d\'attente',
      subtitle: 'Commencez dès aujourd\'hui.',
      cta: 'S\'inscrire maintenant',
      description: 'Soyez parmi les premiers à profiter de l\'expérience MobiSoins et bénéficiez d\'avantages exclusifs au lancement.',
      emailPlaceholder: 'votre@email.com',
      submitButton: 'M\'inscrire',
      submitting: 'Envoi...',
      successTitle: 'Merci !',
      successMessage: 'Vous êtes inscrit à la liste d\'attente.',
      errorTitle: 'Erreur',
      errorMessage: 'Une erreur s\'est produite. Veuillez réessayer.',
      invalidEmailTitle: 'Email invalide',
      priorityAccess: 'Accès prioritaire',
      noCardRequired: 'Pas de carte requise',
    },
    about: {
      badge: 'À propos',
      title: 'À propos',
      missionBadge: 'Notre mission',
      missionTitle: 'Des soins accessibles, où que vous soyez.',
      missionLead: 'Au Québec, obtenir des soins simples peut exiger des heures d\'attente, parfois des jours. MobiSoins existe pour changer cela. Nous amenons l\'expertise clinique directement au domicile des patients, rapidement et en toute sécurité.',
      statementBadge: 'Notre engagement',
      statement1: 'La mission de MobiSoins est de rendre des soins de santé de qualité plus accessibles en offrant des soins sûrs, professionnels et empreints de compassion, directement au domicile des patients, grâce à une plateforme numérique innovante.',
      statement2: 'Nous croyons que personne ne devrait avoir à patienter des heures dans une clinique bondée, ni à traverser la ville, pour recevoir des soins qui peuvent très bien être prodigués là où l\'on vit. En connectant les patients à des infirmières certifiées OIIQ en quelques minutes, MobiSoins efface la distance entre une personne et les soins dont elle a besoin, qu\'il s\'agisse d\'une prise de sang, d\'un pansement, du suivi d\'une maladie chronique ou d\'une visite rassurante auprès d\'un proche.',
      statement3: 'Derrière chaque visite se trouve une équipe qui unit expertise clinique et technologie moderne. Nos infirmières respectent les plus hauts standards de pratique, et notre plateforme rend chaque étape transparente, de la réservation jusqu\'au rapport clinique partagé après la visite. C\'est ainsi que nous bâtissons la confiance, un domicile et un patient à la fois, partout au Québec.',
      problemBadge: 'Le problème',
      problemTitle: 'Un système sous pression, des patients laissés de côté.',
      problemText1: 'Les urgences débordent, les listes d\'attente s\'allongent et une population vieillissante a besoin de soins de plus en plus fréquents. Pour un simple pansement, une prise de sang ou un suivi, des milliers de personnes se déplacent, patientent et perdent un temps précieux.',
      problemText2: 'Pendant ce temps, des infirmières hautement qualifiées manquent d\'outils modernes pour rejoindre efficacement les patients qui ont besoin d\'elles. Le talent existe. La demande existe. Ce qui manquait, c\'était le lien entre les deux.',
      problemText3: 'C\'est précisément pour combler cet écart que MobiSoins a été fondée à Montréal en 2025, par une équipe réunissant plus de 36 années d\'expérience infirmière combinée et des ingénieurs issus de grandes entreprises technologiques comme Microsoft, IBM et Constellation Software.',
      storyBadge: 'Notre histoire',
      storyTitle: 'Tout a commencé par une attente de deux jours.',
      storyText1: 'En septembre 2025, à Montréal, l\'un de nos fondateurs a vu sa mère passer deux journées entières à l\'hôpital. Pas pour une chirurgie, ni pour quoi que ce soit de complexe. Elle attendait un Tylenol et un billet médical. Deux jours, pour quelque chose qui aurait dû prendre quelques minutes. Cette attente a été l\'étincelle de MobiSoins.',
      storyText2: 'Quatre personnes qui avaient vu ce problème des deux côtés ont décidé d\'y remédier. Deux infirmières cliniciennes cumulant plus de 36 années d\'expérience au chevet des patients, et deux ingénieurs logiciels ayant bâti des systèmes à grande échelle chez Microsoft, IBM et Constellation Software. Ils se sont rencontrés par des connaissances communes, partageaient la même frustration, et ont fondé MobiSoins ensemble, à parts égales.',
      storyText3: 'Le problème va dans les deux sens. Les patients attendent beaucoup trop longtemps pour des soins qui pourraient facilement venir à eux, et les infirmières qui prodiguent ces soins sont trop souvent sous-évaluées et sous-payées pour leur expertise. MobiSoins a été créée pour corriger les deux. Nous offrons des soins sûrs, professionnels et empreints de compassion aux patients de tout âge, et nous donnons aux infirmières une meilleure façon, plus juste, d\'exercer.',
      storyText4: 'Nous commençons au Québec, mais notre ambition ne s\'arrête pas là. Notre objectif est de nous étendre à l\'échelle nationale, puis partout dans le monde, afin que chacun, où qu\'il soit, puisse recevoir des soins de qualité dans le confort de son domicile.',
      storyQuote: 'Personne ne devrait attendre deux jours pour un Tylenol.',
      foundersLabel: 'Les fondateurs',
      founderRole: 'Cofondateur',
      fact1Value: '36+',
      fact1Label: 'Années d\'expérience infirmière combinées',
      fact2Value: '2025',
      fact2Label: 'Fondée à Montréal, Québec',
      fact3Value: 'Big tech',
      fact3Label: 'Ingénierie issue de Microsoft, IBM et Constellation',
      teamBadge: 'Notre équipe',
      teamTitle: 'Le soin et la technologie, côte à côte.',
      teamLead: 'On ne peut pas améliorer les soins de santé sans réunir ceux qui les donnent et ceux qui construisent les outils. C\'est pourquoi nos infirmières et nos ingénieurs travaillent dans la même équipe, vers le même objectif.',
      team1Title: 'Rigueur clinique',
      team1Desc: 'Des infirmières certifiées OIIQ définissent chaque protocole de soins et valident chaque fonctionnalité avant qu\'elle atteigne un patient.',
      team2Title: 'Ingénierie de pointe',
      team2Desc: 'Une équipe technique bâtit une plateforme rapide, fiable et sécuritaire, du jumelage en temps réel jusqu\'au dossier clinique.',
      team3Title: 'Ancrage terrain',
      team3Desc: 'Nos opérations restent proches des patients et des infirmières pour améliorer le service en continu, une visite à la fois.',
      valuesBadge: 'Nos valeurs',
      valuesTitle: 'Ce qui nous guide',
      value1Title: 'Accessibilité',
      value1Desc: 'Des soins de qualité pour tous, partout au Québec, sans les longues attentes.',
      value2Title: 'Humanité',
      value2Desc: 'La personne au cœur de chaque intervention, avec écoute et bienveillance.',
      value3Title: 'Excellence clinique',
      value3Desc: 'Des infirmières certifiées OIIQ, tenues aux plus hauts standards de pratique.',
      value4Title: 'Innovation',
      value4Desc: 'La technologie au service de soins plus rapides, sûrs et transparents.',
      description1: 'MobiSoins est une clinique mobile offrant des soins infirmiers professionnels à domicile et en ligne.',
      description2: 'Fondée par deux infirmières cliniciennes, MobiSoins a pour mission de rendre les soins de santé plus accessibles, rapides et sécuritaires, tout en plaçant la personne au cœur de chaque intervention.',
      description3: 'Grâce à une approche moderne alliant expertise clinique et innovation, nous offrons des services adaptés aux besoins de la population, dans le respect des plus hauts standards de pratique.',
      servicesTitle: 'Services',
      servicesIntro: 'MobiSoins offre une gamme complète de soins infirmiers adaptés à vos besoins, à domicile ou en ligne.',
      insuranceNote: 'Certains services sont admissibles au remboursement par assurances privées. Reçus officiels fournis.',
      service1Title: 'Soins infirmiers',
      service1Desc: 'Pansements, retrait de points, administration de médicaments, soins post-opératoires et suivi clinique.',
      service2Title: 'Suivi des maladies chroniques',
      service2Desc: 'Suivi du diabète, de l\'hypertension et autres conditions, avec enseignement et prévention des complications.',
      service3Title: 'Bilan de santé',
      service3Desc: 'Évaluation complète, prise des signes vitaux et conseils personnalisés pour votre santé.',
      service4Title: 'Santé sexuelle',
      service4Desc: 'Dépistage ITSS, contraception, éducation et suivi.',
      service5Title: 'Soins aux aînés',
      service5Desc: 'Surveillance de la santé, gestion de la médication et soutien à domicile.',
      service6Title: 'Analyses et prélèvements',
      service6Desc: 'Prélèvements sanguins et tests diagnostiques, selon ordonnance.',
      service7Title: 'Services aux entreprises',
      service7Desc: 'Cliniques mobiles, bilans de santé et programmes de prévention en milieu de travail.',
    },
    footer: {
      description: 'MobiSoins révolutionne l\'accès aux soins de santé à domicile au Québec.',
      company: 'Entreprise',
      aboutUs: 'À propos',
      press: 'Presse',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'Pour les patients',
      forNurses: 'Pour les infirmières',
      pricing: 'Tarification',
      insurance: 'Assurances',
      support: 'Support',
      helpCenter: 'Centre d\'aide',
      contact: 'Contact',
      privacy: 'Confidentialité',
      terms: 'Conditions',
      legal: 'Légal',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d\'utilisation',
      cookies: 'Politique de cookies',
      allRightsReserved: 'Tous droits réservés.',
    },
  },
  EN: {
    v2: {
      heroBadge: 'Licensed OIIQ nurses · Quebec',
      heroCtaPrimary: 'Join the waitlist',
      heroCtaSecondary: 'See how it works',

      stepsTitle: 'Three steps, no waiting room.',
      stepsEyebrow: 'How it works',
      step1Num: '01', step1Meta: '2 minutes', step1Title: 'Describe the care',
      step1Opt1: 'Blood draw', step1Opt2: 'Wound / dressing', step1Opt3: 'Injection / vaccine',
      step1FootLabel: 'Today', step1FootValue: '2:30 PM',
      step2Num: '02', step2Meta: 'Under 60 s', step2Title: 'We find the nurse',
      step2Chip: 'On the way · 8 min', step2Licence: 'OIIQ licensed',
      step3Num: '03', step3Meta: 'After the visit', step3Title: 'The care, then the report',
      step3Row1: 'Blood pressure', step3Row2: 'Sample',
      step3Row3: 'Sent to your doctor', step3Row3Value: 'Yes',
      step3Row4: 'Insurance receipt', step3Row4Value: 'PDF',
      step3Cta: 'Download',

      cred1Title: 'Licensed nurses',
      cred1Body: 'OIIQ permit verified before the first visit.',
      cred2Title: 'Data stays in Quebec',
      cred2Body: 'Records hosted and encrypted, compliant with Law 25.',
      cred3Title: 'Liability insurance',
      cred3Body: 'Every visit is covered — nothing for you to arrange.',
      cred4Title: 'Insurance receipts',
      cred4Body: 'An eligible receipt is issued automatically after each visit.',

      dispatchEyebrow: 'Live dispatch',
      dispatchTitle1: 'You know where she is,',
      dispatchTitle2: 'to the minute.',
      dispatchBody: 'No phone calls, no four-hour window. An alert five minutes before she rings the bell.',
      dispatchRow1: 'Matching', dispatchRow1Value: 'under 60 s',
      dispatchRow2: 'Coverage', dispatchRow2Value: 'Greater Montreal',
      dispatchRow3: 'Availability', dispatchRow3Value: '7 days a week',
      dispatchEtaLabel: 'Estimated arrival', dispatchEta: '8 min',
      dispatchNurseStatus: 'OIIQ licensed · on the way',
      dispatchMessage: 'Message',

      servicesEyebrow: 'Care offered',
      servicesTitle: 'What a nurse can do in your home.',
      servicesNote: 'Some services are eligible for private insurance reimbursement. An official receipt is provided after every visit.',
      patientsEyebrow: 'Our patients',
      patientsTitle1: 'Care comes to the people',
      patientsTitle2: 'who can no longer',
      patientsTitle3: 'travel to get it.',
      patientsBody: 'Seniors losing independence, patients recovering from surgery, families without a car, caregivers at the end of their rope. For them, a clinic appointment costs half a day — and sometimes adapted transport.',
      nursesEyebrow: 'For nurses',
      nursesPitch: 'Choose your shifts, your areas and the care you want to give.',
      nursesCta: 'Join the network',

      ctaTitle1: 'We launch soon',
      ctaTitle2: 'in Quebec.',
      ctaBody: 'Sign up to be among the first served in your area.',
      ctaButton: 'Sign me up',
      ctaFinePrint: 'No card required. Unsubscribe in one click.',
    },
    header: {
      home: 'Home',
      language: 'Language',
      joinWaitlist: 'Join Waitlist',
      about: 'About',
      howItWorks: 'How It Works',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Download App',
      recruitment: 'Recruitment',
      contact: 'Contact',
    },
    hero: {
      availableInQuebec: 'Available in Quebec',
      title: 'A nurse at your door',
      titleHighlight: 'in minutes',
      subtitle: 'Licensed nurses, booked in a few taps. Professional, secure, available 24/7.',
      subtitleShort: 'Licensed nurses, booked in a few taps.',
      bookNow: 'Join Waitlist',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Waiting List',
      waitlistSubtitle: 'Be the first to know and get',
      waitlistDiscount: '20% off',
      waitlistDiscountSuffix: 'at launch.',
      emailPlaceholder: 'your@email.com',
      successMessage: 'Registered!',
      errorMessage: 'Error',
      invalidEmail: 'Invalid email',
      personsRegistered: 'People registered',
      patientsServed: 'Patients Served',
      nextAppointment: 'Next Appointment',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Network',
      nurses: 'Nurses',
      zone: 'Zone',
      quebec: 'Quebec',
      continueButton: 'Continue',
      or: 'OR',
      continueWithApple: 'Continue with Apple',
      continueWithGoogle: 'Continue with Google',
      continueWithEmail: 'Continue with email address',
      findAccount: 'Find your account',
      phoneNumber: 'Phone number',
      getStarted: 'Get started with MobiSoins',
    },
    howItWorks: {
      title: 'How does it work?',
      subtitle: 'MobiSoins simplifies access to home healthcare.',
      step1Title: 'Book in 2 Minutes',
      step1Description: 'Choose your service, the time that suits you, and confirm your address. Our AI immediately finds available nurses near you.',
      step2Title: 'Matching & Real-Time Tracking',
      step2Description: 'Our algorithm selects the most suitable nurse. Track her travel to you on the map in real-time.',
      step3Title: 'Professional Home Care',
      step3Description: 'Enjoy hospital-quality care in the comfort of your home. Clinical report available in the app after each visit.',
      step1: {
        title: 'Book in 2 Minutes',
        description: 'Choose your service, the time that suits you, and confirm your address. Our AI immediately finds available nurses near you.',
      },
      step2: {
        title: 'Matching & Real-Time Tracking',
        description: 'Our algorithm selects the most suitable nurse. Track her travel to you on the map in real-time.',
      },
      step3: {
        title: 'Professional Home Care',
        description: 'Enjoy hospital-quality care in the comfort of your home. Clinical report available in the app after each visit.',
      },
    },
    services: {
      badge: 'Our Advantages',
      seeAll: 'View all services',
      mainTitle: 'Your health deserves',
      mainTitlePrefix: 'complete',
      mainTitleHighlight: 'services',
      mainTitleSuffix: ' ',
      card1Visual: 'Dashboard',
      card1Item1: 'Next Appt',
      card1Item1Detail: 'Tomorrow, 2:00 PM',
      card1Item2: 'Medications',
      card1Item2Detail: 'Taken at 8:00 AM',
      card1Badge: 'Personalized Tracking',
      card1Title: 'Everything in one place',
      card1Description: 'Manage your appointments, track your prescriptions, and view your care history at a glance.',
      card1Point1: 'Appointment & medication reminders',
      card1Point2: 'Complete care history in the app',
      card1Point3: 'Shareable digital clinical reports',
      card2Visual: 'Smart Search',
      card2Badge: 'Precise Matching',
      card2Title: 'Find the Ideal Expert',
      card2Description: 'Our algorithm instantly connects you with the qualified nurse closest to you.',
      card2Point1: 'OIIQ-certified, background-checked nurses',
      card2Point2: 'AI matching in seconds',
      card2Point3: 'Same-day availability, 24/7',
      card3Visual: 'Your Data',
      card3Badge: 'Clinical Tracking',
      card3Title: 'Visualize your progress',
      card3Description: 'Clear and detailed charts to track your health evolution and easily share your reports.',
      card3Point1: 'Blood draws, wound care & injections',
      card3Point2: 'Post-op, elderly & pediatric care',
      card3Point3: 'Real-time visit & vitals tracking',
      mapBadge: 'Available across Quebec',
      bannerTitle: 'Home care everywhere',
      bannerTitleHighlight: 'in Quebec.',
      bannerDescription: 'OIIQ-certified nurses available in Montreal, Quebec City, Laval, Longueuil, Sherbrooke, Gatineau and throughout the province.',
      bannerCta: 'Join the waiting list',
    },
    patients: {
      badge: 'Our patients',
      title: 'Care that makes people smile',
      subtitle: 'Every day, our nurses bring professional, compassionate care directly to our patients\' homes.',
      description: 'Blood tests, post-operative follow-up, medication administration, wound care or simply a reassuring presence: MobiSoins supports every patient with professionalism and compassion, at every step of their recovery. Our OIIQ-certified nurses travel across Quebec to deliver hospital-quality care, without the stress or the trips.',
      point1Title: 'Personalized care',
      point1Desc: 'Every care plan is tailored to the patient\'s exact needs, in the comfort of home.',
      point2Title: 'Zero travel',
      point2Desc: 'No more long clinic waits. The nurse comes straight to your door.',
      point3Title: 'Full clinical follow-up',
      point3Desc: 'A detailed report after every visit, shared with the patient and their loved ones.',
      point4Title: 'Compassionate support',
      point4Desc: 'Our nurses take the time to listen, explain and reassure.',
    },
    map: {
      badge: 'Real-time dispatch',
      title: 'Home care in just minutes',
      description: 'Our dispatch algorithm automatically connects each patient to the nearest available OIIQ-certified nurse.',
      bullet1: 'Matching in under 60 seconds',
      bullet1Sub: 'We instantly find the nearest available nurse for you.',
      bullet2: 'Verified OIIQ-certified nurses',
      bullet2Sub: 'Every professional is validated and certified by the Order.',
      bullet3: 'Real-time GPS tracking',
      bullet3Sub: 'Follow your nurse\'s journey right to your door.',
      footnote: 'Available across Quebec',
      stepBooked: 'Booked',
      stepMatched: 'Matched',
      stepEnRoute: 'En route',
      stepArrived: 'Arrived',
      trackTitle: 'Visit tracking',
    },
    blog: {
      badge: 'Our Blog',
      title: 'Latest Articles',
      subtitle: 'Stay informed about the latest health news, expert advice, and MobiSoins innovations.',
      readMore: 'Read article',
      readTime: 'read',
      article1Tag1: 'Health Innovation',
      article1Tag2: 'Telehealth',
      article1Title: 'How Telehealth Is Transforming Medical Monitoring',
      article1Description: 'What if consulting a healthcare professional were as simple as a video call? Telehealth is fundamentally transforming medical monitoring.',
      article2Tag1: 'Practical Guide',
      article2Tag2: 'Home',
      article2Title: 'How to Prepare for Your First Visit with MobiSoins',
      article2Description: 'Receiving home nursing care means benefiting from professional follow-up directly in your own environment.',
      article3Tag1: 'Health Trend',
      article3Tag2: 'Seniors',
      article3Title: 'The Benefits of Home Care for Seniors',
      article3Description: 'What if the best place to age wasn\'t the hospital... but simply at home?',
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to your most common questions',
      ctaPrompt: 'Have a question? Check out our frequently asked questions.',
      ctaButton: 'View FAQ',
      searchPlaceholder: 'Search for a question...',
      noResults: 'No questions found for your search.',
      question1: 'How does MobiSoins work?',
      answer1: 'MobiSoins connects patients with certified nurses for home care. You book via the app, track your nurse in real-time, and pay securely after the service.',
      question2: 'Are the nurses really certified?',
      answer2: 'Yes, absolutely. All our nurses are members of the Quebec Order of Nurses (OIIQ), have liability insurance, and have passed our rigorous verification process including background checks.',
      question3: 'What are the costs?',
      answer3: 'Prices vary by service ($45 to $95 on average). The exact price is displayed before booking. No hidden fees. Secure payment by credit card or Apple Pay.',
      question4: 'Which regions are covered?',
      answer4: 'Currently available in Montreal, Quebec City, Laval, Gatineau, Longueuil, and Sherbrooke. Expansion planned in 10+ cities by the end of 2027.',
      question5: 'How to become a partner nurse?',
      answer5: 'Sign up via our \'Become a Nurse\' form. We verify your OIIQ license, insurance, and conduct an interview. You can start accepting missions within 5 business days.',
      question6: 'Are payments secure?',
      answer6: 'Yes, all payments are processed by Stripe, a global leader in payment security. We never store your banking information.',
      question7: 'Can I choose my nurse?',
      answer7: 'You can see the profile, ratings, and experience of the nurse before accepting the mission. If you have a preference, you can request them for your next visits.',
      question8: 'What happens in case of a medical emergency?',
      answer8: 'MobiSoins is NOT an emergency service. In case of a life-threatening emergency, dial 911. Our nurses can handle non-urgent care and direct you to the emergency room if necessary.',
    },
    contact: {
      title: 'Contact Us',
      description: 'Available for questions, feedback, or partnership opportunities. We respond within 24 hours.',
      detailsTitle: 'Contact Details',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      web: 'Web',
      firstName: 'First Name',
      firstNamePlaceholder: 'First Name',
      lastName: 'Last Name',
      lastNamePlaceholder: 'Last Name',
      emailLabel: 'Email',
      emailPlaceholder: 'your@email.com',
      subject: 'Subject',
      subjectPlaceholder: 'How can we help you?',
      message: 'Message',
      messagePlaceholder: 'Describe your request in detail...',
      send: 'Send Message',
      sending: 'Sending...',
      sent: '✓ Message Sent!',
      sentConfirm: 'Thank you! We will respond within 24 hours.',
      errorGeneric: 'Something went wrong. Please try again or email us at info@mobisoins.com.',
      errorConfig: 'The form isn\'t configured yet. Please email us at info@mobisoins.com.',
    },
    stats: {
      patients: 'Patients served',
      nurses: 'OIIQ Nurses',
      satisfaction: 'Satisfaction',
      availability: 'Availability',
      cities: 'Cities in Quebec',
    },
    newsletter: {
      title: 'Join the Waiting List',
      subtitle: 'Get started today.',
      cta: 'Sign up now',
      description: 'Be among the first to experience MobiSoins and enjoy exclusive benefits at launch.',
      emailPlaceholder: 'your@email.com',
      submitButton: 'Sign Up',
      submitting: 'Sending...',
      successTitle: 'Thank you!',
      successMessage: 'You are registered on the waiting list.',
      errorTitle: 'Error',
      errorMessage: 'An error occurred. Please try again.',
      invalidEmailTitle: 'Invalid email',
      priorityAccess: 'Priority access',
      noCardRequired: 'No card required',
    },
    about: {
      badge: 'About',
      title: 'About Us',
      missionBadge: 'Our mission',
      missionTitle: 'Accessible care, wherever you are.',
      missionLead: 'In Quebec, getting simple care can mean hours of waiting, sometimes days. MobiSoins exists to change that. We bring clinical expertise directly to patients\' homes, quickly and safely.',
      statementBadge: 'Our commitment',
      statement1: 'MobiSoins mission is to make quality healthcare more accessible by delivering safe, professional and compassionate care directly to patients\' homes through an innovative digital platform.',
      statement2: 'We believe that no one should have to wait hours in a crowded clinic, or travel across the city, to receive care that can just as easily be provided where they live. By connecting patients with OIIQ-certified nurses in just a few minutes, MobiSoins removes the distance between a person and the care they need, whether it is a blood test, a wound dressing, a chronic condition follow up or a reassuring visit for a loved one.',
      statement3: 'Behind every visit stands a team that pairs clinical expertise with modern technology. Our nurses uphold the highest standards of practice, and our platform keeps every step transparent, from booking to the clinical report shared after the visit. This is how we build trust, one home and one patient at a time, across Quebec.',
      problemBadge: 'The problem',
      problemTitle: 'A system under pressure, patients left behind.',
      problemText1: 'Emergency rooms are overflowing, waitlists keep growing, and an aging population needs care more and more often. For a simple dressing change, a blood test or a follow-up, thousands of people travel, wait and lose precious time.',
      problemText2: 'Meanwhile, highly qualified nurses lack modern tools to efficiently reach the patients who need them. The talent exists. The demand exists. What was missing was the connection between the two.',
      problemText3: 'That is exactly the gap MobiSoins was founded to close, launched in Montreal in 2025 by a team combining more than 36 years of nursing experience with engineers from big tech companies like Microsoft, IBM and Constellation Software.',
      storyBadge: 'Our story',
      storyTitle: 'It started with a two day wait.',
      storyText1: 'In September 2025, in Montreal, one of our founders watched his mother spend two full days in a hospital. Not for surgery, not for anything complex. She was waiting for a Tylenol and a doctor\'s note. Two days, for something that should have taken minutes. That wait was the spark for MobiSoins.',
      storyText2: 'Four people who had seen this problem from both sides decided to fix it. Two clinical nurses with more than 36 years of combined experience at the bedside, and two software engineers who had built large scale systems at Microsoft, IBM and Constellation Software. They met through mutual connections, shared the same frustration, and founded MobiSoins together as equals.',
      storyText3: 'The problem runs two ways. Patients wait far too long for care that could easily come to them, and the nurses who provide that care are too often undervalued and underpaid for their expertise. MobiSoins was built to fix both. We bring safe, professional and compassionate care to patients of every age, and we give nurses a better, fairer way to practice.',
      storyText4: 'We are starting in Quebec, but our ambition does not stop there. Our goal is to expand across the country and then around the world, so that anyone, anywhere, can receive quality healthcare in the comfort of their own home.',
      storyQuote: 'No one should wait two days for a Tylenol.',
      foundersLabel: 'The founders',
      founderRole: 'Cofounder',
      fact1Value: '36+',
      fact1Label: 'Years of combined nursing experience',
      fact2Value: '2025',
      fact2Label: 'Founded in Montreal, Quebec',
      fact3Value: 'Big tech',
      fact3Label: 'Engineering from Microsoft, IBM and Constellation',
      teamBadge: 'Our team',
      teamTitle: 'Care and technology, side by side.',
      teamLead: 'You cannot improve healthcare without bringing together the people who deliver care and the people who build the tools. That is why our nurses and engineers work on the same team, toward the same goal.',
      team1Title: 'Clinical rigor',
      team1Desc: 'OIIQ-certified nurses define every care protocol and validate every feature before it ever reaches a patient.',
      team2Title: 'Serious engineering',
      team2Desc: 'A technical team builds a fast, reliable and secure platform, from real-time matching to the clinical record.',
      team3Title: 'On the ground',
      team3Desc: 'Our operations stay close to patients and nurses to keep improving the service, one visit at a time.',
      valuesBadge: 'Our values',
      valuesTitle: 'What guides us',
      value1Title: 'Accessibility',
      value1Desc: 'Quality care for everyone, everywhere in Quebec, without the long waits.',
      value2Title: 'Humanity',
      value2Desc: 'The person at the heart of every visit, with genuine listening and compassion.',
      value3Title: 'Clinical excellence',
      value3Desc: 'OIIQ-certified nurses held to the highest standards of practice.',
      value4Title: 'Innovation',
      value4Desc: 'Technology in service of faster, safer, more transparent care.',
      description1: 'MobiSoins is a mobile clinic offering professional nursing care at home and online.',
      description2: 'Founded by two clinical nurses, MobiSoins\' mission is to make healthcare more accessible, faster and safer, while placing the person at the heart of every intervention.',
      description3: 'Through a modern approach combining clinical expertise and innovation, we offer services tailored to the needs of the population, in accordance with the highest standards of practice.',
      servicesTitle: 'Services',
      servicesIntro: 'MobiSoins offers a complete range of nursing care tailored to your needs, at home or online.',
      insuranceNote: 'Some services are eligible for reimbursement by private insurance. Official receipts provided.',
      service1Title: 'Nursing Care',
      service1Desc: 'Wound dressing, suture removal, medication administration, post-operative care and clinical follow-up.',
      service2Title: 'Chronic Disease Management',
      service2Desc: 'Diabetes, hypertension and other condition monitoring, with education and complication prevention.',
      service3Title: 'Health Assessment',
      service3Desc: 'Complete evaluation, vital signs monitoring and personalized health advice.',
      service4Title: 'Sexual Health',
      service4Desc: 'STI screening, contraception, education and follow-up.',
      service5Title: 'Senior Care',
      service5Desc: 'Health monitoring, medication management and home support.',
      service6Title: 'Lab Tests & Samples',
      service6Desc: 'Blood draws and diagnostic tests, by prescription.',
      service7Title: 'Corporate Services',
      service7Desc: 'Mobile clinics, health assessments and workplace prevention programs.',
    },
    footer: {
      description: 'MobiSoins is revolutionizing access to home healthcare in Quebec.',
      company: 'Company',
      aboutUs: 'About Us',
      press: 'Press',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'For Patients',
      forNurses: 'For Nurses',
      pricing: 'Pricing',
      insurance: 'Insurance',
      support: 'Support',
      helpCenter: 'Help Center',
      contact: 'Contact',
      privacy: 'Privacy',
      terms: 'Terms',
      legal: 'Legal',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookies: 'Cookie Policy',
      allRightsReserved: 'All rights reserved.',
    },
  },
};



